/// Built-in OpenCode model ids for TeamPilot pickers (Zen + common direct APIs).
///
/// Zen ids match https://opencode.ai/docs/zen . A future [ProviderCapability]
/// may replace this with a live fetch from `https://opencode.ai/zen/v1/models`.
class OpencodeModelCatalog {
  const OpencodeModelCatalog._();

  static const zen = <String>[
    'big-pickle',
    'claude-3-5-haiku',
    'claude-fable-5',
    'claude-haiku-4-5',
    'claude-opus-4-1',
    'claude-opus-4-5',
    'claude-opus-4-6',
    'claude-opus-4-7',
    'claude-opus-4-8',
    'claude-opus-5',
    'claude-sonnet-4',
    'claude-sonnet-4-5',
    'claude-sonnet-4-6',
    'claude-sonnet-5',
    'deepseek-v4-flash',
    'deepseek-v4-flash-free',
    'deepseek-v4-pro',
    'gemini-3-flash',
    'gemini-3-pro',
    'gemini-3.1-pro',
    'gemini-3.5-flash',
    'gemini-3.5-flash-lite',
    'gemini-3.6-flash',
    'glm-4.6',
    'glm-4.7',
    'glm-4.7-free',
    'glm-5',
    'glm-5-free',
    'glm-5.1',
    'glm-5.2',
    'gpt-5',
    'gpt-5-codex',
    'gpt-5-nano',
    'gpt-5.1',
    'gpt-5.1-codex',
    'gpt-5.1-codex-max',
    'gpt-5.1-codex-mini',
    'gpt-5.2',
    'gpt-5.2-codex',
    'gpt-5.3-codex',
    'gpt-5.3-codex-spark',
    'gpt-5.4',
    'gpt-5.4-mini',
    'gpt-5.4-nano',
    'gpt-5.4-pro',
    'gpt-5.5',
    'gpt-5.5-pro',
    'gpt-5.6-luna',
    'gpt-5.6-sol',
    'gpt-5.6-terra',
    'grok-4.5',
    'grok-build-0.1',
    'grok-code',
    'hy3-free',
    'hy3-preview-free',
    'kimi-k2',
    'kimi-k2-thinking',
    'kimi-k2.5',
    'kimi-k2.5-free',
    'kimi-k2.6',
    'kimi-k2.7-code',
    'kimi-k3',
    'laguna-s-2.1-free',
    'ling-2.6-flash-free',
    'ling-3.0-flash-free',
    'ling-3.0-tiny-free',
    'longcat-2.0-free',
    'mimo-v2-flash-free',
    'mimo-v2-omni-free',
    'mimo-v2-pro-free',
    'mimo-v2.5-free',
    'minimax-m2.1',
    'minimax-m2.1-free',
    'minimax-m2.5',
    'minimax-m2.5-free',
    'minimax-m2.7',
    'minimax-m3',
    'minimax-m3-free',
    'nemotron-3-super-free',
    'nemotron-3-ultra-free',
    'north-mini-code-free',
    'qwen3-coder',
    'qwen3.5-plus',
    'qwen3.6-plus',
    'qwen3.6-plus-free',
    'ring-2.6-1t-free',
    'trinity-large-preview-free',
  ];

  static const _byProviderId = <String, List<String>>{
    'opencode': zen,
    'opencode-go': [
      'deepseek-v4-flash',
      'deepseek-v4-pro',
      'glm-5',
      'glm-5.1',
      'glm-5.2',
      'gpt-5.6-luna',
      'grok-4.5',
      'hy3',
      'kimi-k2.5',
      'kimi-k2.6',
      'kimi-k2.7-code',
      'kimi-k3',
      'mimo-v2-omni',
      'mimo-v2-pro',
      'mimo-v2.5',
      'mimo-v2.5-pro',
      'minimax-m2.5',
      'minimax-m2.7',
      'minimax-m3',
      'qwen3.5-plus',
      'qwen3.6-plus',
      'qwen3.7-max',
      'qwen3.7-plus',
      'qwen3.8-max',
    ],
    'openai': ['gpt-4o', 'gpt-4.1', 'gpt-4.1-mini', 'o3', 'o4-mini'],
    'anthropic': [
      'claude-sonnet-4-5',
      'claude-sonnet-4-6',
      'claude-opus-4-6',
      'claude-haiku-4-5',
    ],
    'google': ['gemini-2.0-flash', 'gemini-2.5-pro', 'gemini-3-flash'],
    'deepseek': ['deepseek-chat', 'deepseek-reasoner'],
    'groq': [
      'llama-3.3-70b-versatile',
      'llama-3.1-8b-instant',
      'mixtral-8x7b-32768',
    ],
    'xai': ['grok-3', 'grok-3-mini'],
  };

  static List<String> knownModelsForProvider(String providerId) {
    final id = providerId.trim();
    if (id.isEmpty) return const [];
    return List<String>.unmodifiable(_byProviderId[id] ?? const []);
  }
}
