include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    # Native Rust crate (including Rust test fixtures named *.dart).
    - rust/**
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
