import 'package:flutter/foundation.dart';

import '../../../../models/team_config.dart';
import '../../../session/member_role_provision.dart';
import '../capabilities/config_profile_capability.dart';

/// Codex CLI team-bus integration — fully self-contained inside the per-member
/// `CODEX_HOME`. Codex is TOML/AGENTS.md/command-hook based (not the JSON
/// metadata + http-hook + `--append-system-prompt-file` model of claude/
/// flashskyai), so nothing here touches the shared JSON MCP registry. It writes:
///
///   AGENTS.md   — member identity, additive over codex's base instructions
///                 (vs claude's `--append-system-prompt-file`)
///   config.toml — `[mcp_servers.teammate-bus]` (HTTP + `X-Member`) and the
///                 `[[hooks.Stop]]` idle hook (mixed mode only)
///
/// The Stop hook command is an inline `curl` to the bus `/idle` endpoint: codex
/// reads the hook's stdout as the decision JSON, and `/idle` already returns the
/// `{"decision":"block"}` shape (same as claude's Stop hook), so the response
/// passes straight through — no shim file, no chmod. The launcher adds
/// `--dangerously-bypass-hook-trust` so this self-provisioned hook runs without
/// the interactive trust prompt (see `CodexCliToolAdapter`).
final class CodexConfigProfileCapability implements ConfigProfileCapability {
  const CodexConfigProfileCapability();

  static const toolId = 'codex';
  static const agentsFileName = 'AGENTS.md';
  static const configFileName = 'config.toml';
  static const busMcpServerName = 'teammate-bus';

  /// wait_for_message blocks indefinitely; keep codex's per-server MCP tool
  /// timeout far above any real idle wait (the bus also streams progress
  /// keepalives every 20s). 24h.
  static const busToolTimeoutSec = 86400;

  @override
  Future<void> ensureSessionProfile(ConfigProfileSessionContext ctx) async {}

  @override
  Future<ConfigProfileLaunchContribution> contributeLaunch(
    ConfigProfileLaunchContext ctx,
  ) async {
    final paths = ctx.paths;
    final codexHome = paths.sessionToolDir(
      ctx.scope.teamId,
      ctx.scope.sessionId,
      toolId,
    );

    final member = ctx.member;
    final mixed = ctx.team?.teamMode == TeamMode.mixed;
    final port = _parseBusPort(ctx.busIdleUrl);

    if (member != null && member.isValid) {
      await paths.fs.ensureDir(codexHome);

      // Member identity → AGENTS.md (additive over codex base instructions).
      final prompt = MemberRoleProvision.composeRolePrompt(
        member: member,
        forceTeamLeadDelegateMode: ctx.team?.forceTeamLeadDelegateMode ?? false,
        mixed: mixed,
      ).trim();
      if (prompt.isNotEmpty) {
        await paths.fs.atomicWrite(
          paths.pathContext.join(codexHome, agentsFileName),
          '$prompt\n',
        );
      }

      // Mixed mode: wire team-bus MCP + Stop-hook idle loop into config.toml.
      if (mixed && port != null) {
        await paths.fs.atomicWrite(
          paths.pathContext.join(codexHome, configFileName),
          buildCodexConfigToml(memberId: member.id, port: port),
        );
      }
    }

    return ConfigProfileLaunchContribution(
      environment: {'CODEX_HOME': codexHome},
    );
  }

  /// Builds `$CODEX_HOME/config.toml` for a mixed-mode bus member: the teammate
  /// bus HTTP MCP server (identified by `X-Member`) plus a Stop hook that POSTs
  /// `/idle` and passes the bus's `{decision:block}` response through to codex.
  @visibleForTesting
  static String buildCodexConfigToml({
    required String memberId,
    required int port,
  }) {
    final idleCommand =
        'curl -sS -X POST -H \\"X-Member: $memberId\\" '
        'http://127.0.0.1:$port/idle';
    return '''
# Generated by TeamPilot — codex team-bus session config. Do not edit.

[mcp_servers.$busMcpServerName]
url = "http://127.0.0.1:$port/mcp"
tool_timeout_sec = $busToolTimeoutSec
http_headers = { "X-Member" = "$memberId" }

# Stop hook: never stand down. POST /idle; the bus replies with
# {"decision":"block"} to push the member back into wait_for_message, or {} when
# its idle fuse trips (lets codex stop). curl stdout is read by codex as the
# decision JSON, so the response passes straight through.
[[hooks.Stop]]

[[hooks.Stop.hooks]]
type = "command"
command = "$idleCommand"
timeout = 30
''';
  }

  /// Parses the bus idle URL (e.g. `http://127.0.0.1:12345/idle`) to its port.
  /// MCP (`/mcp`) and idle (`/idle`) share one loopback server, so the port is
  /// all that is needed to reach both.
  static int? _parseBusPort(String? idleUrl) {
    if (idleUrl == null || idleUrl.isEmpty) return null;
    final uri = Uri.tryParse(idleUrl);
    if (uri == null || !uri.hasPort) return null;
    return uri.port;
  }
}
