import 'dart:convert';

import '../../../team_bus/mcp/teammate_bus_mcp_config.dart';
import '../../../team_bus/mcp/teammate_bus_mcp_handler.dart';

/// Builds the per-member Cursor plugin that wires a mixed-mode team member into
/// the TeamPilot bus. Unlike claude/flashskyai/codex, hooks/rules/MCP are NOT
/// read from `$CURSOR_CONFIG_DIR` — they only load from a plugin passed via
/// `--plugin-dir`. So everything bus-related lives in one isolated plugin dir:
///
///   `<pluginDir>/.cursor-plugin/plugin.json`   mcpServers + hooks + rules wiring
///   `<pluginDir>/hooks/hooks.json`             stop hook
///   `<pluginDir>/hooks/idle.sh`                POST /idle, translate decision
///   `<pluginDir>/rules/role.mdc`               alwaysApply member identity
///
/// The `stop` hook posts to the bus `/idle` endpoint and translates the bus's
/// `{"decision":"block",...}` reply into Cursor's `{"followup_message":...}`
/// schema (Cursor has no `decision:block`), keeping the member in its
/// `wait_for_message` loop ("never stand down"). Mirrors [CodexTeamBusOverlay].
abstract final class CursorTeamBusPlugin {
  CursorTeamBusPlugin._();

  static const manifestDirName = '.cursor-plugin';
  static const manifestFileName = 'plugin.json';
  static const hooksDirName = 'hooks';
  static const hooksFileName = 'hooks.json';
  static const idleScriptFileName = 'idle.sh';
  static const rulesDirName = 'rules';
  static const roleRuleFileName = 'role.mdc';

  /// `.cursor-plugin/plugin.json`: registers the teammate-bus MCP server (so the
  /// member gets `wait_for_message`/`send_message`/…), the stop hook, and the
  /// always-apply role rule.
  ///
  /// [hooksPath]/[rulesPath] are **absolute**: Cursor resolves the manifest's
  /// `hooks`/`rules` references relative to the workspace (not the plugin root),
  /// so relative `./…` paths silently fail to load. MCP works regardless since
  /// it is an inline object, not a path reference.
  static Map<String, Object?> manifest({
    required String memberId,
    required int port,
    required String hooksPath,
    required String rulesPath,
  }) => {
    'name': 'teampilot-bus-$memberId',
    'description': 'TeamPilot mixed-mode team-bus wiring (generated).',
    'hooks': hooksPath,
    'rules': rulesPath,
    'mcpServers': {
      teammateBusMcpServerName: teammateBusMcpServerConfig(
        endpoint: Uri.parse('http://127.0.0.1:$port/mcp'),
        memberId: memberId,
      ),
    },
  };

  /// `hooks/hooks.json`: fire [idleScriptPath] on `stop`. `loop_limit: null`
  /// disables Cursor's default 5-iteration cap so the bus loop never auto-ends.
  /// Invoked via `bash <path>` so it needs no executable bit (Filesystem has no
  /// chmod, and SFTP/SSH backends differ).
  static Map<String, Object?> hooksConfig({required String idleScriptPath}) => {
    'version': 1,
    'hooks': {
      'stop': [
        {'command': "bash '$idleScriptPath'", 'loop_limit': null},
      ],
    },
  };

  /// `hooks/idle.sh`: POST the bus `/idle` endpoint (member is now idle), then
  /// translate a `decision:block` reply into a `followup_message` so Cursor
  /// re-prompts the member to call `wait_for_message`. When the bus releases the
  /// member (idle fuse → `{}`), emit nothing and let the turn end.
  static String idleScript({required String memberId, required int port}) {
    final followup = jsonEncode({
      'followup_message': TeammateBusMcpHandler.stopRedirectReason,
    });
    return '''
#!/usr/bin/env bash
# Generated by TeamPilot — cursor team-bus stop hook. Do not edit.
set -u
# Drain the stop-hook stdin payload; we key off the bus reply, not the payload.
cat >/dev/null 2>&1 || true
resp="\$(curl -sS -X POST -H 'X-Member: $memberId' 'http://127.0.0.1:$port/idle' 2>/dev/null || true)"
case "\$resp" in
  *'"decision":"block"'*)
    printf '%s' '$followup'
    ;;
esac
exit 0
''';
  }

  static int? parseBusPort(String? idleUrl) {
    if (idleUrl == null || idleUrl.isEmpty) return null;
    final uri = Uri.tryParse(idleUrl);
    if (uri == null || !uri.hasPort) return null;
    return uri.port;
  }
}
