import '../../host/host_script_dialect.dart';

/// Generates Codex command-hook scripts for HTTP POST (bash / PowerShell).
abstract final class CodexHttpHookScript {
  CodexHttpHookScript._();

  static String build({
    required HostScriptDialect dialect,
    required String url,
    required Map<String, String> headers,
    String? jsonBody,
    bool passResponseToStdout = false,
    int timeoutSec = 30,
  }) {
    return switch (dialect) {
      HostScriptDialect.bash => _bash(
        url: url,
        headers: headers,
        jsonBody: jsonBody,
        passResponseToStdout: passResponseToStdout,
      ),
      HostScriptDialect.powershell => _powershell(
        url: url,
        headers: headers,
        jsonBody: jsonBody,
        passResponseToStdout: passResponseToStdout,
        timeoutSec: timeoutSec,
      ),
    };
  }

  static String _bash({
    required String url,
    required Map<String, String> headers,
    String? jsonBody,
    required bool passResponseToStdout,
  }) {
    final headerArgs = headers.entries
        .map((e) => "-H ${_bashSingleQuote('${e.key}: ${e.value}')}")
        .join(' ');
    final bodyArg = jsonBody == null ? '' : '-d ${_bashSingleQuote(jsonBody)} ';
    final redirect = passResponseToStdout ? '' : ' >/dev/null';
    return '''
#!/usr/bin/env bash
# Generated by TeamPilot — codex HTTP hook. Do not edit.
set -u
curl -sS -X POST $headerArgs$bodyArg${_bashSingleQuote(url)}$redirect || exit 1
exit 0
''';
  }

  static String _powershell({
    required String url,
    required Map<String, String> headers,
    String? jsonBody,
    required bool passResponseToStdout,
    required int timeoutSec,
  }) {
    final headerLines = headers.entries
        .map(
          (e) =>
              "  ${_psSingleQuote(e.key)} = ${_psSingleQuote(e.value)}",
        )
        .join('\n');
    final bodyLine = jsonBody == null
        ? ''
        : '\n\$body = ${_psSingleQuote(jsonBody)}';
    final invokeArgs = jsonBody == null
        ? '-Method Post -Headers \$headers'
        : '-Method Post -Headers \$headers -Body \$body';
    final stdout = passResponseToStdout
        ? '''
  if (\$null -ne \$response.Content -and \$response.Content.Length -gt 0) {
    Write-Output \$response.Content
  }'''
        : '';
    return '''
# Generated by TeamPilot — codex HTTP hook. Do not edit.
\$ErrorActionPreference = 'Stop'
\$headers = @{
$headerLines
}
$bodyLine
try {
  \$response = Invoke-WebRequest -Uri ${_psSingleQuote(url)} $invokeArgs -TimeoutSec $timeoutSec -UseBasicParsing$stdout
} catch {
  exit 1
}
exit 0
''';
  }

  static String _bashSingleQuote(String value) =>
      "'${value.replaceAll("'", "'\\''")}'";

  static String _psSingleQuote(String value) =>
      "'${value.replaceAll("'", "''")}'";
}
