import '../../host/host_script_dialect.dart';
import '../../host/host_script_runner.dart';
import '../../io/filesystem.dart';
import '../../team_bus/member_bus_idle_endpoint.dart';
import 'codex_command_hook_provisioner.dart';
import 'codex_http_hook_script.dart';

/// Mixed-mode team-bus fragments appended to a member's Codex `config.toml`.
abstract final class CodexTeamBusOverlay {
  CodexTeamBusOverlay._();

  static const busMcpServerName = 'teammate-bus';
  static const _hooksDirName = 'hooks';
  static const _stopScriptBaseName = 'teampilot-team-bus-stop';

  /// wait_for_message blocks indefinitely; keep codex's per-server MCP tool
  /// timeout far above any real idle wait (the bus also streams progress
  /// keepalives every 20s). 24h.
  static const busToolTimeoutSec = 86400;

  /// Auto-run all tools on this server (list_teammates, wait_for_message, …)
  /// without per-call approval prompts.
  static const defaultToolsApprovalMode = 'approve';

  /// Full overlay for **local** mixed members: HTTP MCP + Stop hook on one port.
  static Future<String> buildLocal({
    required Filesystem fs,
    required HostScriptRunner runner,
    required String codexHome,
    required String memberId,
    required MemberBusIdleEndpoint idle,
  }) async {
    final port = idle.port;
    if (port == null) {
      throw ArgumentError('idle endpoint has no port: ${idle.url}');
    }
    return '${buildLocalMcpHttp(memberId: memberId, port: port, idle: idle)}\n\n'
        '${await provisionStopHook(
          fs: fs,
          runner: runner,
          codexHome: codexHome,
          memberId: memberId,
          idle: idle,
        )}';
  }

  /// Stop hook only — remote members get MCP via session `extraMcpServers` relay.
  static Future<String> provisionStopHook({
    required Filesystem fs,
    required HostScriptRunner runner,
    required String codexHome,
    required String memberId,
    required MemberBusIdleEndpoint idle,
  }) async {
    final hooksDir = fs.pathContext.join(codexHome, _hooksDirName);
    final provisioner = CodexCommandHookProvisioner(fs: fs, runner: runner);
    final headers = idle.headersFor(memberId);
    final commands = await provisioner.provisionHookCommands(
      hooksDir: hooksDir,
      baseFileName: _stopScriptBaseName,
      scriptBody: CodexHttpHookScript.build(
        dialect: HostScriptDialect.bash,
        url: idle.url,
        headers: headers,
        passResponseToStdout: true,
      ),
      windowsScriptBody: CodexHttpHookScript.build(
        dialect: HostScriptDialect.powershell,
        url: idle.url,
        headers: headers,
        passResponseToStdout: true,
      ),
    );
    return '''
# Generated by TeamPilot — codex team-bus stop hook. Do not edit.

${provisioner.hookToml(
  event: 'Stop',
  command: commands.command,
  commandWindows: commands.commandWindows,
)}
'''
        .trim();
  }

  static String buildLocalMcpHttp({
    required String memberId,
    required int port,
    required MemberBusIdleEndpoint idle,
  }) {
    final headerToml = idle
        .headersFor(memberId)
        .entries
        .map((e) => '"${e.key}" = "${e.value}"')
        .join(', ');
    return '''
# Generated by TeamPilot — codex team-bus MCP (local). Do not edit.

[mcp_servers.$busMcpServerName]
url = "http://127.0.0.1:$port/mcp"
tool_timeout_sec = $busToolTimeoutSec
default_tools_approval_mode = "$defaultToolsApprovalMode"
http_headers = { $headerToml }
'''
        .trim();
  }

  static bool containsOverlay(String toml) =>
      toml.contains('[mcp_servers.$busMcpServerName]') ||
      toml.contains('codex team-bus stop hook');
}
