import '../../agent_status/member_agent_status_endpoint.dart';

/// Agent-status curl hooks appended to a member's Codex `config.toml`.
///
/// Installed whenever [MemberAgentStatusEndpoint] is stamped (simple + team),
/// not gated on mixed mode. Mixed-only Stop→`/idle` stays in
/// [CodexTeamBusOverlay].
///
/// No trust entries: TeamPilot's existing Stop→`/idle` curl hooks also omit
/// Codex hook-trust promotion.
abstract final class CodexAgentStatusOverlay {
  CodexAgentStatusOverlay._();

  static const _events = [
    'PermissionRequest',
    'PreToolUse',
    'PostToolUse',
    'Stop',
    'UserPromptSubmit',
  ];

  /// Curl hooks posting to [endpoint.url] with [endpoint.headersFor].
  ///
  /// Each event embeds `-d '{"hook_event_name":"<Event>"}'` so
  /// [AgentStatusNormalizer] can map the body (Stop→`/idle` posts empty and
  /// does not need a body; `/agent-status` does).
  static String build({
    required String memberId,
    required MemberAgentStatusEndpoint endpoint,
  }) {
    final headerArgs = [
      ...endpoint
          .headersFor(memberId)
          .entries
          .map((e) => '-H \\"${e.key}: ${e.value}\\"'),
      '-H \\"Content-Type: application/json\\"',
    ].join(' ');
    final buffer = StringBuffer(
      '# Generated by TeamPilot — codex agent-status hooks. Do not edit.\n',
    );
    for (final event in _events) {
      // Single-quoted shell -d so JSON double-quotes stay literal; TOML
      // double-quoted command string still needs \" for those quotes.
      final body = '-d \'{\\"hook_event_name\\":\\"$event\\"}\'';
      final command =
          'curl -sS -X POST $headerArgs $body ${endpoint.url}';
      buffer.writeln();
      buffer.writeln('[[hooks.$event]]');
      buffer.writeln();
      buffer.writeln('[[hooks.$event.hooks]]');
      buffer.writeln('type = "command"');
      buffer.writeln('command = "$command"');
      buffer.writeln('timeout = 30');
    }
    return buffer.toString().trim();
  }

  static bool containsOverlay(String toml) =>
      toml.contains('codex agent-status hooks');
}
