import '../../team_bus/member_bus_idle_endpoint.dart';

/// Mixed-mode team-bus fragments appended to a member's Codex `config.toml`.
abstract final class CodexTeamBusOverlay {
  CodexTeamBusOverlay._();

  static const busMcpServerName = 'teammate-bus';

  /// wait_for_message blocks indefinitely; keep codex's per-server MCP tool
  /// timeout far above any real idle wait (the bus also streams progress
  /// keepalives every 20s). 24h.
  static const busToolTimeoutSec = 86400;

  /// Auto-run all tools on this server (list_teammates, wait_for_message, …)
  /// without per-call approval prompts.
  static const defaultToolsApprovalMode = 'approve';

  /// Full overlay for **local** mixed members: HTTP MCP + Stop hook on one port.
  static String buildLocal({
    required String memberId,
    required MemberBusIdleEndpoint idle,
  }) {
    final port = idle.port;
    if (port == null) {
      throw ArgumentError('idle endpoint has no port: ${idle.url}');
    }
    return '${buildLocalMcpHttp(memberId: memberId, port: port, idle: idle)}\n\n'
        '${buildStopHook(memberId: memberId, idle: idle)}';
  }

  /// Stop hook only — remote members get MCP via session `extraMcpServers` relay.
  static String buildStopHook({
    required String memberId,
    required MemberBusIdleEndpoint idle,
  }) {
    final headerArgs = idle
        .headersFor(memberId)
        .entries
        .map((e) => '-H \\"${e.key}: ${e.value}\\"')
        .join(' ');
    final idleCommand = 'curl -sS -X POST $headerArgs ${idle.url}';
    return '''
# Generated by TeamPilot — codex team-bus stop hook. Do not edit.

[[hooks.Stop]]

[[hooks.Stop.hooks]]
type = "command"
command = "$idleCommand"
timeout = 30
'''
        .trim();
  }

  static String buildLocalMcpHttp({
    required String memberId,
    required int port,
    required MemberBusIdleEndpoint idle,
  }) {
    final headerToml = idle
        .headersFor(memberId)
        .entries
        .map((e) => '"${e.key}" = "${e.value}"')
        .join(', ');
    return '''
# Generated by TeamPilot — codex team-bus MCP (local). Do not edit.

[mcp_servers.$busMcpServerName]
url = "http://127.0.0.1:$port/mcp"
tool_timeout_sec = $busToolTimeoutSec
default_tools_approval_mode = "$defaultToolsApprovalMode"
http_headers = { $headerToml }
'''
        .trim();
  }

  static bool containsOverlay(String toml) =>
      toml.contains('[mcp_servers.$busMcpServerName]') ||
      toml.contains('codex team-bus stop hook');
}
