/// Mixed-mode team-bus fragments appended to a member's Codex `config.toml`.
abstract final class CodexTeamBusOverlay {
  CodexTeamBusOverlay._();

  static const busMcpServerName = 'teammate-bus';

  /// wait_for_message blocks indefinitely; keep codex's per-server MCP tool
  /// timeout far above any real idle wait (the bus also streams progress
  /// keepalives every 20s). 24h.
  static const busToolTimeoutSec = 86400;

  static String build({required String memberId, required int port}) {
    final idleCommand =
        'curl -sS -X POST -H \\"X-Member: $memberId\\" '
        'http://127.0.0.1:$port/idle';
    return '''
# Generated by TeamPilot — codex team-bus overlay. Do not edit.

[mcp_servers.$busMcpServerName]
url = "http://127.0.0.1:$port/mcp"
tool_timeout_sec = $busToolTimeoutSec
http_headers = { "X-Member" = "$memberId" }

[[hooks.Stop]]

[[hooks.Stop.hooks]]
type = "command"
command = "$idleCommand"
timeout = 30
'''
        .trim();
  }

  static bool containsOverlay(String toml) =>
      toml.contains('[mcp_servers.$busMcpServerName]');
}
