// GENERATED by tool/gen_warmup_glyphs.dart — do not edit.
// Re-run after editing app_en.arb / app_zh.arb:
//   dart run tool/gen_warmup_glyphs.dart
//
// Every unique glyph across the l10n bundles. [UiWarmup] shapes
// these at startup so the first CJK text render does not pay the
// one-time Noto Sans SC shaping cost on the UI thread.

/// 751 unique glyphs from app_en.arb + app_zh.arb.
const warmupGlyphs = ' !"#\$%&\'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~·–—“”…↑→↓≥①②③✨、。「」一上下不与专且个中为主久么义之也了事二于互些交产享亮亲人仅仍从仓他代令以们件任份休优会传但位低住体作你使例供依侧便保信修值假做停储允先克入全公兰共关其具内册再写冲况准凑凭出击分切划列则刚创删别到制刷刺前剪副力功加务动助包化匹区协单卡危即却卸历压厘原参及友发取受变叠口另只可台史右号各合同名后向否吧含启告员周命和响哪唯商器回因团围固图在地址均块型域基堆塞填境增墨处备复外多大天失夸夹奖套如始委子字存它安完官定实审容宽密对导将小少尚就局层展属工左己已布常干并广序库应底度建开弃式引强归当录形影往径待循心必忆志快忽态怎性总恢息情想意成我或户所手才打托执扩扫找承技把抓折护报拆拉择持指按挑换据授排探接控推描提插搜摘撤操支收改放效数整文新方施旁无日旧时明星是显晰智暂更替最有服期未本机杂权束条来松板极构析林果查标栈栏树校根格框案档检森概模次止正此步段每比求汇沙沟没沿法泛注洁洋活派浅测浏海消涉深混添清源滚滤点然版牌状独环现珀理琥生用由界留略登白的盖盘目直相省看知石码研础确磁示禁离种称移程稍稿空突窗立端符第等筛签简算管箱类粘系索紧紫约级组细终经绑结给络绝统继绪续维缓编缘缩缺网罗置者而聊职联能自至致航色节若范草荐获菜藏行表被装要覆见观规视览角解言计认让议记许论设访证识词试话询该详语误说请读调谱责败账质贴赖起跑距跟跨路跳踪身转软载辑输边迁过运近返还这进远连述退送适选逗通速遵邀部都配里重量钟钥钮链销错键长闭问闲间阅队阶阻附际限除险隆随隐隔需非面页顶项顺须预领题额风首验骤高默（），：；？';

