#!/usr/bin/env bash
# Activate TeamPilot's forked fastforge (client/third_party/fastforge) with local
# flutter_app_packager so AppImage packaging emits StartupWMClass.
# Upstream PR: https://github.com/fastforgedev/fastforge/pull/360
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
FF="$ROOT/client/third_party/fastforge"
CLI="$FF/packages/fastforge"

if [[ ! -d "$CLI" ]]; then
  echo "Missing $CLI — run: git submodule update --init client/third_party/fastforge" >&2
  exit 1
fi

# pubspec_overrides are gitignored in the fastforge monorepo; write them so
# path-activated CLI resolves packager from this checkout (not pub.dev).
write_overrides() {
  local pkg=$1
  shift
  local out="$FF/packages/$pkg/pubspec_overrides.yaml"
  {
    echo '# Generated by tool/activate_fastforge.sh — do not commit.'
    echo 'dependency_overrides:'
    for name in "$@"; do
      printf '  %s:\n    path: ../%s\n' "$name" "$name"
    done
  } >"$out"
}

LOCAL_PKGS=(
  flutter_app_builder
  flutter_app_packager
  flutter_app_publisher
  flutter_distributor
  parse_app_package
  shell_executor
  shell_uikit
  unified_distributor
)

write_overrides fastforge "${LOCAL_PKGS[@]}"
write_overrides unified_distributor "${LOCAL_PKGS[@]}"
write_overrides flutter_distributor "${LOCAL_PKGS[@]}"
write_overrides flutter_app_packager shell_executor
write_overrides flutter_app_builder shell_executor
write_overrides flutter_app_publisher shell_executor
write_overrides parse_app_package shell_executor
write_overrides shell_uikit shell_executor

(
  cd "$CLI"
  dart pub get
  dart pub global activate --source path .
)

echo "Activated fastforge from $CLI"
fastforge --version 2>/dev/null || true
