// ignore_for_file: avoid_print
//
// Generates the startup font-warmup glyph set from the l10n bundles. Run from
// `client/` (and re-run whenever app_en.arb / app_zh.arb change, same cadence
// as `flutter gen-l10n`):
//
//   dart run tool/gen_warmup_glyphs.dart
//
// Why: the UI font is Noto Sans SC (a multi-MB CJK face). Flutter shapes glyphs
// lazily on first use, so the first screen that renders Chinese text pays a
// large one-time HarfBuzz face-init + shaping cost (~300ms). [UiWarmup] shapes
// these glyphs offscreen at startup instead. Driving the glyph set from the ARB
// files keeps coverage complete and self-maintaining — no hand-written string.

import 'dart:convert';
import 'dart:io';

const _arbFiles = ['lib/l10n/app_en.arb', 'lib/l10n/app_zh.arb'];
const _outputFile = 'lib/widgets/warmup_glyphs.g.dart';

void main() {
  final codePoints = <int>{};

  for (final relativePath in _arbFiles) {
    final file = File(relativePath);
    if (!file.existsSync()) {
      stderr.writeln('Missing ARB file: $relativePath');
      exit(1);
    }
    final decoded = jsonDecode(file.readAsStringSync()) as Map<String, dynamic>;
    for (final entry in decoded.entries) {
      // Skip metadata keys (`@@locale`, `@key` resource attributes).
      if (entry.key.startsWith('@')) continue;
      final value = entry.value;
      if (value is! String) continue;
      for (final rune in value.runes) {
        // Drop control chars (newlines/tabs) — nothing to shape there.
        if (rune < 0x20 || rune == 0x7f) continue;
        codePoints.add(rune);
      }
    }
  }

  // Always include the printable ASCII range: paths, numbers, and CLI commands
  // shown in the workbench aren't all guaranteed to appear in the ARB strings.
  for (var c = 0x20; c < 0x7f; c++) {
    codePoints.add(c);
  }

  final sorted = codePoints.toList()..sort();
  final glyphs = String.fromCharCodes(sorted);

  final buffer = StringBuffer()
    ..writeln('// GENERATED by tool/gen_warmup_glyphs.dart — do not edit.')
    ..writeln('// Re-run after editing app_en.arb / app_zh.arb:')
    ..writeln('//   dart run tool/gen_warmup_glyphs.dart')
    ..writeln('//')
    ..writeln('// Every unique glyph across the l10n bundles. [UiWarmup] shapes')
    ..writeln('// these at startup so the first CJK text render does not pay the')
    ..writeln('// one-time Noto Sans SC shaping cost on the UI thread.')
    ..writeln()
    ..writeln('/// ${sorted.length} unique glyphs from app_en.arb + app_zh.arb.')
    ..writeln("const warmupGlyphs = '${_escape(glyphs)}';")
    ..writeln();

  File(_outputFile).writeAsStringSync(buffer.toString());
  print('Wrote $_outputFile (${sorted.length} glyphs).');
}

String _escape(String input) {
  final out = StringBuffer();
  for (final unit in input.runes) {
    switch (unit) {
      case 0x5c: // backslash
        out.write(r'\\');
      case 0x27: // single quote
        out.write(r"\'");
      case 0x24: // dollar sign
        out.write(r'\$');
      default:
        out.writeCharCode(unit);
    }
  }
  return out.toString();
}
