import '../app_provider_config.dart';

/// Claude CLI provider presets (part 4 of 4). Aggregated by [ClaudeProviderPresets].
const List<AppProviderPreset> claudeProviderPresetsPart4 = <AppProviderPreset>[
    AppProviderPreset(
      id: "ctok-ai",
      label: "CTok.ai",
      template: AppProviderConfig(
        id: "ctok-ai",
        cli: CliTool.claude,
        name: "CTok.ai",
        websiteUrl: "https://ctok.ai",
        apiKeyUrl: "https://ctok.ai",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.ctok.ai",
        defaultModel: "",
        icon: "ctok",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ctok",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "e-flowcode",
      label: "E-FlowCode",
      template: AppProviderConfig(
        id: "e-flowcode",
        cli: CliTool.claude,
        name: "E-FlowCode",
        websiteUrl: "https://e-flowcode.cc",
        apiKeyUrl: "https://e-flowcode.cc",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://e-flowcode.cc",
        defaultModel: "",
        icon: "eflowcode",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://e-flowcode.cc"],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "lionccapi",
      label: "LionCCAPI",
      template: AppProviderConfig(
        id: "lionccapi",
        cli: CliTool.claude,
        name: "LionCCAPI",
        websiteUrl: "https://vibecodingapi.ai",
        apiKeyUrl: "",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://vibecodingapi.ai",
        defaultModel: "",
        icon: "lioncc",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "lionccapi",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "openrouter",
      label: "OpenRouter",
      template: AppProviderConfig(
        id: "openrouter",
        cli: CliTool.claude,
        name: "OpenRouter",
        websiteUrl: "https://openrouter.ai",
        apiKeyUrl: "https://openrouter.ai/keys",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://openrouter.ai/api",
        defaultModel: "anthropic/claude-sonnet-4.6",
        icon: "openrouter",
        iconColor: "#6566F1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "models": {
            "anthropic/claude-sonnet-4.6": {"name": "anthropic/claude-sonnet-4.6", "model": "anthropic/claude-sonnet-4.6", "enabled": true},
            "anthropic/claude-haiku-4.5": {"name": "anthropic/claude-haiku-4.5", "model": "anthropic/claude-haiku-4.5", "enabled": true, "role": "background"},
          },
        }
      ),
    ),
    AppProviderPreset(
      id: "therouter",
      label: "TheRouter",
      template: AppProviderConfig(
        id: "therouter",
        cli: CliTool.claude,
        name: "TheRouter",
        websiteUrl: "https://therouter.ai",
        apiKeyUrl: "https://dashboard.therouter.ai",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.therouter.ai",
        defaultModel: "anthropic/claude-sonnet-4.6",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.therouter.ai"],
        config: {
          "models": {
            "anthropic/claude-sonnet-4.6": {"name": "anthropic/claude-sonnet-4.6", "model": "anthropic/claude-sonnet-4.6", "enabled": true},
            "anthropic/claude-haiku-4.5": {"name": "anthropic/claude-haiku-4.5", "model": "anthropic/claude-haiku-4.5", "enabled": true, "role": "background"},
          },
        }
      ),
    ),
    AppProviderPreset(
      id: "novita-ai",
      label: "Novita AI",
      template: AppProviderConfig(
        id: "novita-ai",
        cli: CliTool.claude,
        name: "Novita AI",
        websiteUrl: "https://novita.ai",
        apiKeyUrl: "https://novita.ai",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.novita.ai/anthropic",
        defaultModel: "zai-org/glm-5",
        icon: "novita",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.novita.ai/anthropic"],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "github-copilot",
      label: "GitHub Copilot",
      template: AppProviderConfig(
        id: "github-copilot",
        cli: CliTool.claude,
        name: "GitHub Copilot",
        websiteUrl: "https://github.com/features/copilot",
        apiKeyUrl: "",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.githubcopilot.com",
        defaultModel: "claude-sonnet-4.6",
        icon: "github",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "models": {
            "claude-sonnet-4.6": {"name": "claude-sonnet-4.6", "model": "claude-sonnet-4.6", "enabled": true},
            "claude-haiku-4.5": {"name": "claude-haiku-4.5", "model": "claude-haiku-4.5", "enabled": true, "role": "background"},
          },
          "apiFormat": "openai_chat",
          "providerType": "github_copilot",
          "requiresOAuth": true,
        }
      ),
    ),
    AppProviderPreset(
      id: "codex",
      label: "Codex",
      template: AppProviderConfig(
        id: "codex",
        cli: CliTool.claude,
        name: "Codex",
        websiteUrl: "https://openai.com/chatgpt/pricing",
        apiKeyUrl: "",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://chatgpt.com/backend-api/codex",
        defaultModel: "gpt-5.4",
        icon: "openai",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "models": {
            "gpt-5.4": {"name": "gpt-5.4", "model": "gpt-5.4", "enabled": true},
            "gpt-5.4-mini": {"name": "gpt-5.4-mini", "model": "gpt-5.4-mini", "enabled": true, "role": "background"},
          },
          "apiFormat": "openai_responses",
          "providerType": "codex_oauth",
          "requiresOAuth": true,
        }
      ),
    ),
    AppProviderPreset(
      id: "lemondata",
      label: "LemonData",
      template: AppProviderConfig(
        id: "lemondata",
        cli: CliTool.claude,
        name: "LemonData",
        websiteUrl: "https://lemondata.cc",
        apiKeyUrl: "https://lemondata.cc/r/FFX1ZDUP",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_API_KEY",
        baseUrl: "https://api.lemondata.cc",
        defaultModel: "",
        icon: "lemondata",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "lemondata",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "nvidia",
      label: "Nvidia",
      template: AppProviderConfig(
        id: "nvidia",
        cli: CliTool.claude,
        name: "Nvidia",
        websiteUrl: "https://build.nvidia.com",
        apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://integrate.api.nvidia.com",
        defaultModel: "moonshotai/kimi-k2.5",
        icon: "nvidia",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "apiFormat": "openai_chat",
        }
      ),
    ),
    AppProviderPreset(
      id: "pipellm",
      label: "PIPELLM",
      template: AppProviderConfig(
        id: "pipellm",
        cli: CliTool.claude,
        name: "PIPELLM",
        websiteUrl: "https://code.pipellm.ai",
        apiKeyUrl: "https://code.pipellm.ai/login?ref=uvw650za",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://cc-api.pipellm.ai",
        defaultModel: "claude-opus-4-7",
        icon: "pipellm",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "models": {
            "claude-opus-4-7": {"name": "claude-opus-4-7", "model": "claude-opus-4-7", "enabled": true},
            "claude-haiku-4-5-20251001": {"name": "claude-haiku-4-5-20251001", "model": "claude-haiku-4-5-20251001", "enabled": true, "role": "background"},
          },
        }
      ),
    ),
    AppProviderPreset(
      id: "xiaomi-mimo",
      label: "Xiaomi MiMo",
      template: AppProviderConfig(
        id: "xiaomi-mimo",
        cli: CliTool.claude,
        name: "Xiaomi MiMo",
        websiteUrl: "https://platform.xiaomimimo.com",
        apiKeyUrl: "https://platform.xiaomimimo.com/#/console/api-keys",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.xiaomimimo.com/anthropic",
        defaultModel: "mimo-v2-pro",
        icon: "xiaomimimo",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "aws-bedrock-aksk",
      label: "AWS Bedrock (AKSK)",
      template: AppProviderConfig(
        id: "aws-bedrock-aksk",
        cli: CliTool.claude,
        name: "AWS Bedrock (AKSK)",
        websiteUrl: "https://aws.amazon.com/bedrock/",
        apiKeyUrl: "",
        category: AppProviderCategory.cloudProvider,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://bedrock-runtime.\${AWS_REGION}.amazonaws.com",
        defaultModel: "global.anthropic.claude-opus-4-7",
        icon: "aws",
        iconColor: "#FF9900",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "models": {
            "global.anthropic.claude-opus-4-7": {"name": "global.anthropic.claude-opus-4-7", "model": "global.anthropic.claude-opus-4-7", "enabled": true},
            "global.anthropic.claude-haiku-4-5-20251001-v1:0": {"name": "global.anthropic.claude-haiku-4-5-20251001-v1:0", "model": "global.anthropic.claude-haiku-4-5-20251001-v1:0", "enabled": true, "role": "background"},
          },
          "env": {
            "AWS_ACCESS_KEY_ID": "\${AWS_ACCESS_KEY_ID}",
            "AWS_SECRET_ACCESS_KEY": "\${AWS_SECRET_ACCESS_KEY}",
            "AWS_REGION": "\${AWS_REGION}",
            "CLAUDE_CODE_USE_BEDROCK": "1",
          },
          "templateValues": {
            "AWS_REGION": {
              "label": "AWS Region",
              "placeholder": "us-west-2",
              "editorValue": "us-west-2",
            },
            "AWS_ACCESS_KEY_ID": {
              "label": "Access Key ID",
              "placeholder": "AKIA...",
              "editorValue": "",
            },
            "AWS_SECRET_ACCESS_KEY": {
              "label": "Secret Access Key",
              "placeholder": "your-secret-key",
              "editorValue": "",
            },
          },
        }
      ),
    ),
    AppProviderPreset(
      id: "aws-bedrock-api-key",
      label: "AWS Bedrock (API Key)",
      template: AppProviderConfig(
        id: "aws-bedrock-api-key",
        cli: CliTool.claude,
        name: "AWS Bedrock (API Key)",
        websiteUrl: "https://aws.amazon.com/bedrock/",
        apiKeyUrl: "",
        category: AppProviderCategory.cloudProvider,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://bedrock-runtime.\${AWS_REGION}.amazonaws.com",
        defaultModel: "global.anthropic.claude-opus-4-7",
        icon: "aws",
        iconColor: "#FF9900",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "models": {
            "global.anthropic.claude-opus-4-7": {"name": "global.anthropic.claude-opus-4-7", "model": "global.anthropic.claude-opus-4-7", "enabled": true},
            "global.anthropic.claude-haiku-4-5-20251001-v1:0": {"name": "global.anthropic.claude-haiku-4-5-20251001-v1:0", "model": "global.anthropic.claude-haiku-4-5-20251001-v1:0", "enabled": true, "role": "background"},
          },
          "env": {
            "AWS_REGION": "\${AWS_REGION}",
            "CLAUDE_CODE_USE_BEDROCK": "1",
          },
          "templateValues": {
            "AWS_REGION": {
              "label": "AWS Region",
              "placeholder": "us-west-2",
              "editorValue": "us-west-2",
            },
          },
        }
      ),
    ),
];
