import '../app_provider_config.dart';

/// Claude CLI provider presets (part 1 of 4). Aggregated by [ClaudeProviderPresets].
const List<AppProviderPreset> claudeProviderPresetsPart1 = <AppProviderPreset>[
    AppProviderPreset(
      id: "claude-official",
      label: "Claude Official",
      template: AppProviderConfig(
        id: "claude-official",
        cli: CliTool.claude,
        name: "Claude Official",
        websiteUrl: "https://www.anthropic.com/claude-code",
        apiKeyUrl: "",
        category: AppProviderCategory.official,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "",
        defaultModel: "",
        icon: "anthropic",
        iconColor: "#D4915D",
        isOfficial: true,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {"env": {}},
      ),
    ),
    AppProviderPreset(
      id: "shengsuanyun",
      label: "Shengsuanyun",
      template: AppProviderConfig(
        id: "shengsuanyun",
        cli: CliTool.claude,
        name: "Shengsuanyun",
        websiteUrl: "https://www.shengsuanyun.com",
        apiKeyUrl: "https://www.shengsuanyun.com/?from=CH_4HHXMRYF",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://router.shengsuanyun.com/api",
        defaultModel: "",
        icon: "shengsuanyun",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "shengsuanyun",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://router.shengsuanyun.com/api",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "patewayai",
      label: "PatewayAI",
      template: AppProviderConfig(
        id: "patewayai",
        cli: CliTool.claude,
        name: "PatewayAI",
        websiteUrl: "https://pateway.ai",
        apiKeyUrl: "https://pateway.ai/?ch=etzpm8&aff=WB6M6F67#/",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_API_KEY",
        baseUrl: "https://api.pateway.ai",
        defaultModel: "",
        icon: "pateway",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "patewayai",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.pateway.ai",
            "ANTHROPIC_API_KEY": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "agentplan",
      label: "火山Agentplan",
      template: AppProviderConfig(
        id: "agentplan",
        cli: CliTool.claude,
        name: "火山Agentplan",
        websiteUrl:
            "https://www.volcengine.com/activity/agentplan?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        apiKeyUrl:
            "https://www.volcengine.com/activity/agentplan?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
        defaultModel: "ark-code-latest",
        icon: "huoshan",
        iconColor: "#3370FF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "volcengine_agentplan",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://ark.cn-beijing.volces.com/api/coding",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "ark-code-latest",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "byteplus",
      label: "BytePlus",
      template: AppProviderConfig(
        id: "byteplus",
        cli: CliTool.claude,
        name: "BytePlus",
        websiteUrl:
            "https://www.byteplus.com/en/product/modelark?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        apiKeyUrl:
            "https://www.byteplus.com/en/product/modelark?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding",
        defaultModel: "ark-code-latest",
        icon: "byteplus",
        iconColor: "#3370FF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "byteplus",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://ark.ap-southeast.bytepluses.com/api/coding",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "ark-code-latest",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "doubaoseed",
      label: "DouBaoSeed",
      template: AppProviderConfig(
        id: "doubaoseed",
        cli: CliTool.claude,
        name: "DouBaoSeed",
        websiteUrl:
            "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey?apikey=%7B%7D&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        apiKeyUrl:
            "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey?apikey=%7B%7D&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
        defaultModel: "doubao-seed-2-0-code-preview-latest",
        icon: "doubao",
        iconColor: "#3370FF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "doubaoseed",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://ark.cn-beijing.volces.com/api/compatible",
            "ANTHROPIC_AUTH_TOKEN": "",
            "API_TIMEOUT_MS": "3000000",
            "ANTHROPIC_MODEL": "doubao-seed-2-0-code-preview-latest",
            "ANTHROPIC_DEFAULT_SONNET_MODEL":
                "doubao-seed-2-0-code-preview-latest",
            "ANTHROPIC_DEFAULT_OPUS_MODEL":
                "doubao-seed-2-0-code-preview-latest",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL":
                "doubao-seed-2-0-code-preview-latest",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "gemini-native",
      label: "Gemini Native",
      template: AppProviderConfig(
        id: "gemini-native",
        cli: CliTool.claude,
        name: "Gemini Native",
        websiteUrl: "https://ai.google.dev/gemini-api",
        apiKeyUrl: "https://aistudio.google.com/app/apikey",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_API_KEY",
        baseUrl: "https://generativelanguage.googleapis.com",
        defaultModel: "gemini-3.1-pro",
        icon: "gemini",
        iconColor: "#4285F4",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://generativelanguage.googleapis.com"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://generativelanguage.googleapis.com",
            "ANTHROPIC_API_KEY": "",
            "ANTHROPIC_MODEL": "gemini-3.1-pro",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "gemini-3-flash",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "gemini-3.1-pro",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "gemini-3.1-pro",
          },
          "apiFormat": "gemini_native",
        },
      ),
    ),
    AppProviderPreset(
      id: "deepseek",
      label: "DeepSeek",
      template: AppProviderConfig(
        id: "deepseek",
        cli: CliTool.claude,
        name: "DeepSeek",
        websiteUrl: "https://platform.deepseek.com",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.deepseek.com/anthropic",
        defaultModel: "deepseek-v4-pro",
        icon: "deepseek",
        iconColor: "#1E88E5",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.deepseek.com/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "deepseek-v4-pro",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "deepseek-v4-flash",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "deepseek-v4-pro",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "deepseek-v4-pro",
          },
          "modelsUrl": "https://api.deepseek.com/models",
        },
      ),
    ),
    AppProviderPreset(
      id: "zhipu-glm",
      label: "Zhipu GLM",
      template: AppProviderConfig(
        id: "zhipu-glm",
        cli: CliTool.claude,
        name: "Zhipu GLM",
        websiteUrl: "https://open.bigmodel.cn",
        apiKeyUrl: "https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://open.bigmodel.cn/api/anthropic",
        defaultModel: "glm-5",
        icon: "zhipu",
        iconColor: "#0F62FE",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://open.bigmodel.cn/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "glm-5",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "zhipu-glm-en",
      label: "Zhipu GLM en",
      template: AppProviderConfig(
        id: "zhipu-glm-en",
        cli: CliTool.claude,
        name: "Zhipu GLM en",
        websiteUrl: "https://z.ai",
        apiKeyUrl: "https://z.ai/subscribe?ic=8JVLJQFSKB",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.z.ai/api/anthropic",
        defaultModel: "glm-5",
        icon: "zhipu",
        iconColor: "#0F62FE",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.z.ai/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "glm-5",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "baidu-qianfan-coding-plan",
      label: "Baidu Qianfan Coding Plan",
      template: AppProviderConfig(
        id: "baidu-qianfan-coding-plan",
        cli: CliTool.claude,
        name: "Baidu Qianfan Coding Plan",
        websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
        apiKeyUrl:
            "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://qianfan.baidubce.com/anthropic/coding",
        defaultModel: "qianfan-code-latest",
        icon: "baidu",
        iconColor: "#2932E1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://qianfan.baidubce.com/anthropic/coding"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://qianfan.baidubce.com/anthropic/coding",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "qianfan-code-latest",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "qianfan-code-latest",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "qianfan-code-latest",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "qianfan-code-latest",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "bailian",
      label: "Bailian",
      template: AppProviderConfig(
        id: "bailian",
        cli: CliTool.claude,
        name: "Bailian",
        websiteUrl: "https://bailian.console.aliyun.com",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
        defaultModel: "",
        icon: "bailian",
        iconColor: "#624AFF",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://dashscope.aliyuncs.com/apps/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "bailian-for-coding",
      label: "Bailian For Coding",
      template: AppProviderConfig(
        id: "bailian-for-coding",
        cli: CliTool.claude,
        name: "Bailian For Coding",
        websiteUrl: "https://bailian.console.aliyun.com",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
        defaultModel: "",
        icon: "bailian",
        iconColor: "#624AFF",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://coding.dashscope.aliyuncs.com/apps/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "kimi",
      label: "Kimi",
      template: AppProviderConfig(
        id: "kimi",
        cli: CliTool.claude,
        name: "Kimi",
        websiteUrl: "https://platform.moonshot.cn/console",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.moonshot.cn/anthropic",
        defaultModel: "kimi-k2.6",
        icon: "kimi",
        iconColor: "#6366F1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.moonshot.cn/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "kimi-k2.6",
          },
        },
      ),
    ),
];
