import '../app_provider_config.dart';

class ClaudeProviderPresets {
  const ClaudeProviderPresets._();

  static const all = <AppProviderPreset>[
    AppProviderPreset(
      id: "claude-official",
      label: "Claude Official",
      template: AppProviderConfig(
        id: "claude-official",
        cli: AppProviderCli.claude,
        name: "Claude Official",
        websiteUrl: "https://www.anthropic.com/claude-code",
        apiKeyUrl: "",
        category: AppProviderCategory.official,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "",
        defaultModel: "",
        icon: "anthropic",
        iconColor: "#D4915D",
        isOfficial: true,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {"env": {}},
      ),
    ),
    AppProviderPreset(
      id: "shengsuanyun",
      label: "Shengsuanyun",
      template: AppProviderConfig(
        id: "shengsuanyun",
        cli: AppProviderCli.claude,
        name: "Shengsuanyun",
        websiteUrl: "https://www.shengsuanyun.com",
        apiKeyUrl: "https://www.shengsuanyun.com/?from=CH_4HHXMRYF",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://router.shengsuanyun.com/api",
        defaultModel: "",
        icon: "shengsuanyun",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "shengsuanyun",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://router.shengsuanyun.com/api",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "patewayai",
      label: "PatewayAI",
      template: AppProviderConfig(
        id: "patewayai",
        cli: AppProviderCli.claude,
        name: "PatewayAI",
        websiteUrl: "https://pateway.ai",
        apiKeyUrl: "https://pateway.ai/?ch=etzpm8&aff=WB6M6F67#/",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_API_KEY",
        baseUrl: "https://api.pateway.ai",
        defaultModel: "",
        icon: "pateway",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "patewayai",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.pateway.ai",
            "ANTHROPIC_API_KEY": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "agentplan",
      label: "火山Agentplan",
      template: AppProviderConfig(
        id: "agentplan",
        cli: AppProviderCli.claude,
        name: "火山Agentplan",
        websiteUrl:
            "https://www.volcengine.com/activity/agentplan?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        apiKeyUrl:
            "https://www.volcengine.com/activity/agentplan?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://ark.cn-beijing.volces.com/api/coding",
        defaultModel: "ark-code-latest",
        icon: "huoshan",
        iconColor: "#3370FF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "volcengine_agentplan",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://ark.cn-beijing.volces.com/api/coding",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "ark-code-latest",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "byteplus",
      label: "BytePlus",
      template: AppProviderConfig(
        id: "byteplus",
        cli: AppProviderCli.claude,
        name: "BytePlus",
        websiteUrl:
            "https://www.byteplus.com/en/product/modelark?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        apiKeyUrl:
            "https://www.byteplus.com/en/product/modelark?utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://ark.ap-southeast.bytepluses.com/api/coding",
        defaultModel: "ark-code-latest",
        icon: "byteplus",
        iconColor: "#3370FF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "byteplus",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://ark.ap-southeast.bytepluses.com/api/coding",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "ark-code-latest",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "ark-code-latest",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "doubaoseed",
      label: "DouBaoSeed",
      template: AppProviderConfig(
        id: "doubaoseed",
        cli: AppProviderCli.claude,
        name: "DouBaoSeed",
        websiteUrl:
            "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey?apikey=%7B%7D&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        apiKeyUrl:
            "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey?apikey=%7B%7D&utm_campaign=hw&utm_content=ccswitch&utm_medium=devrel_tool_web&utm_source=OWO&utm_term=ccswitch",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://ark.cn-beijing.volces.com/api/compatible",
        defaultModel: "doubao-seed-2-0-code-preview-latest",
        icon: "doubao",
        iconColor: "#3370FF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "doubaoseed",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://ark.cn-beijing.volces.com/api/compatible",
            "ANTHROPIC_AUTH_TOKEN": "",
            "API_TIMEOUT_MS": "3000000",
            "ANTHROPIC_MODEL": "doubao-seed-2-0-code-preview-latest",
            "ANTHROPIC_DEFAULT_SONNET_MODEL":
                "doubao-seed-2-0-code-preview-latest",
            "ANTHROPIC_DEFAULT_OPUS_MODEL":
                "doubao-seed-2-0-code-preview-latest",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL":
                "doubao-seed-2-0-code-preview-latest",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "gemini-native",
      label: "Gemini Native",
      template: AppProviderConfig(
        id: "gemini-native",
        cli: AppProviderCli.claude,
        name: "Gemini Native",
        websiteUrl: "https://ai.google.dev/gemini-api",
        apiKeyUrl: "https://aistudio.google.com/app/apikey",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_API_KEY",
        baseUrl: "https://generativelanguage.googleapis.com",
        defaultModel: "gemini-3.1-pro",
        icon: "gemini",
        iconColor: "#4285F4",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://generativelanguage.googleapis.com"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://generativelanguage.googleapis.com",
            "ANTHROPIC_API_KEY": "",
            "ANTHROPIC_MODEL": "gemini-3.1-pro",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "gemini-3-flash",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "gemini-3.1-pro",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "gemini-3.1-pro",
          },
          "apiFormat": "gemini_native",
        },
      ),
    ),
    AppProviderPreset(
      id: "deepseek",
      label: "DeepSeek",
      template: AppProviderConfig(
        id: "deepseek",
        cli: AppProviderCli.claude,
        name: "DeepSeek",
        websiteUrl: "https://platform.deepseek.com",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.deepseek.com/anthropic",
        defaultModel: "deepseek-v4-pro",
        icon: "deepseek",
        iconColor: "#1E88E5",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.deepseek.com/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "deepseek-v4-pro",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "deepseek-v4-flash",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "deepseek-v4-pro",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "deepseek-v4-pro",
          },
          "modelsUrl": "https://api.deepseek.com/models",
        },
      ),
    ),
    AppProviderPreset(
      id: "zhipu-glm",
      label: "Zhipu GLM",
      template: AppProviderConfig(
        id: "zhipu-glm",
        cli: AppProviderCli.claude,
        name: "Zhipu GLM",
        websiteUrl: "https://open.bigmodel.cn",
        apiKeyUrl: "https://www.bigmodel.cn/claude-code?ic=RRVJPB5SII",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://open.bigmodel.cn/api/anthropic",
        defaultModel: "glm-5",
        icon: "zhipu",
        iconColor: "#0F62FE",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://open.bigmodel.cn/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "glm-5",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "zhipu-glm-en",
      label: "Zhipu GLM en",
      template: AppProviderConfig(
        id: "zhipu-glm-en",
        cli: AppProviderCli.claude,
        name: "Zhipu GLM en",
        websiteUrl: "https://z.ai",
        apiKeyUrl: "https://z.ai/subscribe?ic=8JVLJQFSKB",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.z.ai/api/anthropic",
        defaultModel: "glm-5",
        icon: "zhipu",
        iconColor: "#0F62FE",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.z.ai/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "glm-5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "glm-5",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "baidu-qianfan-coding-plan",
      label: "Baidu Qianfan Coding Plan",
      template: AppProviderConfig(
        id: "baidu-qianfan-coding-plan",
        cli: AppProviderCli.claude,
        name: "Baidu Qianfan Coding Plan",
        websiteUrl: "https://cloud.baidu.com/product/qianfan_modelbuilder",
        apiKeyUrl:
            "https://console.bce.baidu.com/qianfan/ais/console/applicationConsole/application",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://qianfan.baidubce.com/anthropic/coding",
        defaultModel: "qianfan-code-latest",
        icon: "baidu",
        iconColor: "#2932E1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://qianfan.baidubce.com/anthropic/coding"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://qianfan.baidubce.com/anthropic/coding",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "qianfan-code-latest",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "qianfan-code-latest",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "qianfan-code-latest",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "qianfan-code-latest",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "bailian",
      label: "Bailian",
      template: AppProviderConfig(
        id: "bailian",
        cli: AppProviderCli.claude,
        name: "Bailian",
        websiteUrl: "https://bailian.console.aliyun.com",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://dashscope.aliyuncs.com/apps/anthropic",
        defaultModel: "",
        icon: "bailian",
        iconColor: "#624AFF",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://dashscope.aliyuncs.com/apps/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "bailian-for-coding",
      label: "Bailian For Coding",
      template: AppProviderConfig(
        id: "bailian-for-coding",
        cli: AppProviderCli.claude,
        name: "Bailian For Coding",
        websiteUrl: "https://bailian.console.aliyun.com",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://coding.dashscope.aliyuncs.com/apps/anthropic",
        defaultModel: "",
        icon: "bailian",
        iconColor: "#624AFF",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://coding.dashscope.aliyuncs.com/apps/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "kimi",
      label: "Kimi",
      template: AppProviderConfig(
        id: "kimi",
        cli: AppProviderCli.claude,
        name: "Kimi",
        websiteUrl: "https://platform.moonshot.cn/console",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.moonshot.cn/anthropic",
        defaultModel: "kimi-k2.6",
        icon: "kimi",
        iconColor: "#6366F1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.moonshot.cn/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "kimi-k2.6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "kimi-k2.6",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "kimi-for-coding",
      label: "Kimi For Coding",
      template: AppProviderConfig(
        id: "kimi-for-coding",
        cli: AppProviderCli.claude,
        name: "Kimi For Coding",
        websiteUrl: "https://www.kimi.com/code/docs/",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.kimi.com/coding/",
        defaultModel: "",
        icon: "kimi",
        iconColor: "#6366F1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.kimi.com/coding/",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "stepfun",
      label: "StepFun",
      template: AppProviderConfig(
        id: "stepfun",
        cli: AppProviderCli.claude,
        name: "StepFun",
        websiteUrl: "https://platform.stepfun.com/step-plan",
        apiKeyUrl: "https://platform.stepfun.com/interface-key",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.stepfun.com/step_plan",
        defaultModel: "step-3.5-flash-2603",
        icon: "stepfun",
        iconColor: "#16D6D2",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.stepfun.com/step_plan"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.stepfun.com/step_plan",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "step-3.5-flash-2603",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "step-3.5-flash-2603",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "step-3.5-flash-2603",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "step-3.5-flash-2603",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "stepfun-en",
      label: "StepFun en",
      template: AppProviderConfig(
        id: "stepfun-en",
        cli: AppProviderCli.claude,
        name: "StepFun en",
        websiteUrl: "https://platform.stepfun.ai/step-plan",
        apiKeyUrl: "https://platform.stepfun.ai/interface-key",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.stepfun.ai/step_plan",
        defaultModel: "step-3.5-flash-2603",
        icon: "stepfun",
        iconColor: "#16D6D2",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.stepfun.ai/step_plan"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.stepfun.ai/step_plan",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "step-3.5-flash-2603",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "step-3.5-flash-2603",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "step-3.5-flash-2603",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "step-3.5-flash-2603",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "modelscope",
      label: "ModelScope",
      template: AppProviderConfig(
        id: "modelscope",
        cli: AppProviderCli.claude,
        name: "ModelScope",
        websiteUrl: "https://modelscope.cn",
        apiKeyUrl: "",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api-inference.modelscope.cn",
        defaultModel: "ZhipuAI/GLM-5",
        icon: "modelscope",
        iconColor: "#624AFF",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api-inference.modelscope.cn",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "ZhipuAI/GLM-5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "ZhipuAI/GLM-5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "ZhipuAI/GLM-5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "ZhipuAI/GLM-5",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "kat-coder",
      label: "KAT-Coder",
      template: AppProviderConfig(
        id: "kat-coder",
        cli: AppProviderCli.claude,
        name: "KAT-Coder",
        websiteUrl: "https://console.streamlake.ai",
        apiKeyUrl: "https://console.streamlake.ai/console/api-key",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl:
            "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/\${ENDPOINT_ID}/claude-code-proxy",
        defaultModel: "KAT-Coder-Pro V1",
        icon: "catcoder",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/\${ENDPOINT_ID}/claude-code-proxy",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "KAT-Coder-Pro V1",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "KAT-Coder-Air V1",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "KAT-Coder-Pro V1",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "KAT-Coder-Pro V1",
          },
          "templateValues": {
            "ENDPOINT_ID": {
              "label": "Vanchin Endpoint ID",
              "placeholder": "ep-xxx-xxx",
              "defaultValue": "",
              "editorValue": "",
            },
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "longcat",
      label: "Longcat",
      template: AppProviderConfig(
        id: "longcat",
        cli: AppProviderCli.claude,
        name: "Longcat",
        websiteUrl: "https://longcat.chat/platform",
        apiKeyUrl: "https://longcat.chat/platform/api_keys",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.longcat.chat/anthropic",
        defaultModel: "LongCat-Flash-Chat",
        icon: "longcat",
        iconColor: "#29E154",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.longcat.chat/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "LongCat-Flash-Chat",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "LongCat-Flash-Chat",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "LongCat-Flash-Chat",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "LongCat-Flash-Chat",
            "CLAUDE_CODE_MAX_OUTPUT_TOKENS": "6000",
            "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": 1,
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "minimax",
      label: "MiniMax",
      template: AppProviderConfig(
        id: "minimax",
        cli: AppProviderCli.claude,
        name: "MiniMax",
        websiteUrl: "https://platform.minimaxi.com",
        apiKeyUrl: "https://platform.minimaxi.com/subscribe/coding-plan",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.minimaxi.com/anthropic",
        defaultModel: "MiniMax-M2.7",
        icon: "minimax",
        iconColor: "#FF6B6B",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "minimax_cn",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.minimaxi.com/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "API_TIMEOUT_MS": "3000000",
            "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": 1,
            "ANTHROPIC_MODEL": "MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "MiniMax-M2.7",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "minimax-en",
      label: "MiniMax en",
      template: AppProviderConfig(
        id: "minimax-en",
        cli: AppProviderCli.claude,
        name: "MiniMax en",
        websiteUrl: "https://platform.minimax.io",
        apiKeyUrl: "https://platform.minimax.io/subscribe/coding-plan",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.minimax.io/anthropic",
        defaultModel: "MiniMax-M2.7",
        icon: "minimax",
        iconColor: "#FF6B6B",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "minimax_en",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.minimax.io/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "API_TIMEOUT_MS": "3000000",
            "CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC": 1,
            "ANTHROPIC_MODEL": "MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "MiniMax-M2.7",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "bailing",
      label: "BaiLing",
      template: AppProviderConfig(
        id: "bailing",
        cli: AppProviderCli.claude,
        name: "BaiLing",
        websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.tbox.cn/api/anthropic",
        defaultModel: "Ling-2.5-1T",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.tbox.cn/api/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "Ling-2.5-1T",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "Ling-2.5-1T",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "Ling-2.5-1T",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "Ling-2.5-1T",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aihubmix",
      label: "AiHubMix",
      template: AppProviderConfig(
        id: "aihubmix",
        cli: AppProviderCli.claude,
        name: "AiHubMix",
        websiteUrl: "https://aihubmix.com",
        apiKeyUrl: "https://aihubmix.com",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_API_KEY",
        baseUrl: "https://aihubmix.com",
        defaultModel: "",
        icon: "aihubmix",
        iconColor: "#006FFB",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [
          "https://aihubmix.com",
          "https://api.aihubmix.com",
        ],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://aihubmix.com",
            "ANTHROPIC_API_KEY": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "siliconflow",
      label: "SiliconFlow",
      template: AppProviderConfig(
        id: "siliconflow",
        cli: AppProviderCli.claude,
        name: "SiliconFlow",
        websiteUrl: "https://siliconflow.cn",
        apiKeyUrl: "https://cloud.siliconflow.cn/i/drGuwc9k",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.siliconflow.cn",
        defaultModel: "Pro/MiniMaxAI/MiniMax-M2.7",
        icon: "siliconflow",
        iconColor: "#6E29F6",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "siliconflow",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.siliconflow.cn",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "Pro/MiniMaxAI/MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "Pro/MiniMaxAI/MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "Pro/MiniMaxAI/MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "Pro/MiniMaxAI/MiniMax-M2.7",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "siliconflow-en",
      label: "SiliconFlow en",
      template: AppProviderConfig(
        id: "siliconflow-en",
        cli: AppProviderCli.claude,
        name: "SiliconFlow en",
        websiteUrl: "https://siliconflow.com",
        apiKeyUrl: "https://cloud.siliconflow.cn/i/drGuwc9k",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.siliconflow.com",
        defaultModel: "MiniMaxAI/MiniMax-M2.7",
        icon: "siliconflow",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "siliconflow",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.siliconflow.com",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "MiniMaxAI/MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "MiniMaxAI/MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "MiniMaxAI/MiniMax-M2.7",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "MiniMaxAI/MiniMax-M2.7",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "dmxapi",
      label: "DMXAPI",
      template: AppProviderConfig(
        id: "dmxapi",
        cli: AppProviderCli.claude,
        name: "DMXAPI",
        websiteUrl: "https://www.dmxapi.cn",
        apiKeyUrl: "https://www.dmxapi.cn",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.dmxapi.cn",
        defaultModel: "",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "dmxapi",
        endpointCandidates: ["https://www.dmxapi.cn", "https://api.dmxapi.cn"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://www.dmxapi.cn",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "packycode",
      label: "PackyCode",
      template: AppProviderConfig(
        id: "packycode",
        cli: AppProviderCli.claude,
        name: "PackyCode",
        websiteUrl: "https://www.packyapi.com",
        apiKeyUrl: "https://www.packyapi.com/register?aff=cc-switch",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.packyapi.com",
        defaultModel: "",
        icon: "packycode",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "packycode",
        endpointCandidates: [
          "https://www.packyapi.com",
          "https://api-slb.packyapi.com",
        ],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://www.packyapi.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "claudeapi",
      label: "ClaudeAPI",
      template: AppProviderConfig(
        id: "claudeapi",
        cli: AppProviderCli.claude,
        name: "ClaudeAPI",
        websiteUrl: "https://claudeapi.com",
        apiKeyUrl: "https://console.claudeapi.com/register?aff=pCLD",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://gw.claudeapi.com",
        defaultModel: "",
        icon: "claudeapi",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "claudeapi",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://gw.claudeapi.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "claudecn",
      label: "ClaudeCN",
      template: AppProviderConfig(
        id: "claudecn",
        cli: AppProviderCli.claude,
        name: "ClaudeCN",
        websiteUrl: "https://claudecn.top",
        apiKeyUrl: "https://claudecn.top/register?aff=ccswitch",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://claudecn.top",
        defaultModel: "",
        icon: "claudecn",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "claudecn",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://claudecn.top",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "runapi",
      label: "RunAPI",
      template: AppProviderConfig(
        id: "runapi",
        cli: AppProviderCli.claude,
        name: "RunAPI",
        websiteUrl: "https://runapi.co",
        apiKeyUrl: "https://runapi.co",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://runapi.co",
        defaultModel: "",
        icon: "runapi",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "runapi",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://runapi.co",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "relaxycode",
      label: "RelaxyCode",
      template: AppProviderConfig(
        id: "relaxycode",
        cli: AppProviderCli.claude,
        name: "RelaxyCode",
        websiteUrl: "https://www.relaxycode.com",
        apiKeyUrl: "https://www.relaxycode.com/register",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.relaxycode.com",
        defaultModel: "",
        icon: "relaxcode",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://www.relaxycode.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "cubence",
      label: "Cubence",
      template: AppProviderConfig(
        id: "cubence",
        cli: AppProviderCli.claude,
        name: "Cubence",
        websiteUrl: "https://cubence.com",
        apiKeyUrl: "https://cubence.com/signup?code=CCSWITCH&source=ccs",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.cubence.com",
        defaultModel: "",
        icon: "cubence",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "cubence",
        endpointCandidates: [
          "https://api.cubence.com",
          "https://api-cf.cubence.com",
          "https://api-dmit.cubence.com",
          "https://api-bwg.cubence.com",
        ],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.cubence.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aigocode",
      label: "AIGoCode",
      template: AppProviderConfig(
        id: "aigocode",
        cli: AppProviderCli.claude,
        name: "AIGoCode",
        websiteUrl: "https://aigocode.com",
        apiKeyUrl: "https://aigocode.com/invite/CC-SWITCH",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.aigocode.com",
        defaultModel: "",
        icon: "aigocode",
        iconColor: "#5B7FFF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aigocode",
        endpointCandidates: ["https://api.aigocode.com"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.aigocode.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "rightcode",
      label: "RightCode",
      template: AppProviderConfig(
        id: "rightcode",
        cli: AppProviderCli.claude,
        name: "RightCode",
        websiteUrl: "https://www.right.codes",
        apiKeyUrl: "https://www.right.codes/register?aff=CCSWITCH",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.right.codes/claude",
        defaultModel: "",
        icon: "rc",
        iconColor: "#E96B2C",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "rightcode",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://www.right.codes/claude",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aicodemirror",
      label: "AICodeMirror",
      template: AppProviderConfig(
        id: "aicodemirror",
        cli: AppProviderCli.claude,
        name: "AICodeMirror",
        websiteUrl: "https://www.aicodemirror.com",
        apiKeyUrl: "https://www.aicodemirror.com/register?invitecode=9915W3",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.aicodemirror.com/api/claudecode",
        defaultModel: "",
        icon: "aicodemirror",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aicodemirror",
        endpointCandidates: [
          "https://api.aicodemirror.com/api/claudecode",
          "https://api.claudecode.net.cn/api/claudecode",
        ],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.aicodemirror.com/api/claudecode",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aicoding",
      label: "AICoding",
      template: AppProviderConfig(
        id: "aicoding",
        cli: AppProviderCli.claude,
        name: "AICoding",
        websiteUrl: "https://aicoding.sh",
        apiKeyUrl: "https://aicoding.sh/i/CCSWITCH",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.aicoding.sh",
        defaultModel: "",
        icon: "aicoding",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aicoding",
        endpointCandidates: ["https://api.aicoding.sh"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.aicoding.sh",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "crazyrouter",
      label: "CrazyRouter",
      template: AppProviderConfig(
        id: "crazyrouter",
        cli: AppProviderCli.claude,
        name: "CrazyRouter",
        websiteUrl: "https://www.crazyrouter.com",
        apiKeyUrl:
            "https://www.crazyrouter.com/register?aff=OZcm&ref=cc-switch",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://cn.crazyrouter.com",
        defaultModel: "",
        icon: "crazyrouter",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "crazyrouter",
        endpointCandidates: ["https://cn.crazyrouter.com"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://cn.crazyrouter.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "sssaicode",
      label: "SSSAiCode",
      template: AppProviderConfig(
        id: "sssaicode",
        cli: AppProviderCli.claude,
        name: "SSSAiCode",
        websiteUrl: "https://www.sssaicode.com",
        apiKeyUrl: "https://www.sssaicode.com/register?ref=DCP0SM",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://node-hk.sssaicode.com/api",
        defaultModel: "",
        icon: "sssaicode",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "sssaicode",
        endpointCandidates: [
          "https://node-hk.sssaicode.com/api",
          "https://claude2.sssaicode.com/api",
          "https://anti.sssaicode.com/api",
        ],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://node-hk.sssaicode.com/api",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "compshare",
      label: "Compshare",
      template: AppProviderConfig(
        id: "compshare",
        cli: AppProviderCli.claude,
        name: "Compshare",
        websiteUrl: "https://www.compshare.cn",
        apiKeyUrl:
            "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.modelverse.cn",
        defaultModel: "",
        icon: "ucloud",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ucloud",
        endpointCandidates: ["https://api.modelverse.cn"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.modelverse.cn",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "compshare-coding-plan",
      label: "Compshare Coding Plan",
      template: AppProviderConfig(
        id: "compshare-coding-plan",
        cli: AppProviderCli.claude,
        name: "Compshare Coding Plan",
        websiteUrl: "https://www.compshare.cn",
        apiKeyUrl:
            "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://cp.compshare.cn",
        defaultModel: "",
        icon: "ucloud",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ucloud",
        endpointCandidates: ["https://cp.compshare.cn"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://cp.compshare.cn",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "micu",
      label: "Micu",
      template: AppProviderConfig(
        id: "micu",
        cli: AppProviderCli.claude,
        name: "Micu",
        websiteUrl: "https://www.micuapi.ai",
        apiKeyUrl: "https://www.micuapi.ai/register?aff=aOYQ",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.micuapi.ai",
        defaultModel: "",
        icon: "micu",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "micu",
        endpointCandidates: ["https://www.micuapi.ai"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://www.micuapi.ai",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "ctok-ai",
      label: "CTok.ai",
      template: AppProviderConfig(
        id: "ctok-ai",
        cli: AppProviderCli.claude,
        name: "CTok.ai",
        websiteUrl: "https://ctok.ai",
        apiKeyUrl: "https://ctok.ai",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.ctok.ai",
        defaultModel: "",
        icon: "ctok",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ctok",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.ctok.ai",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "e-flowcode",
      label: "E-FlowCode",
      template: AppProviderConfig(
        id: "e-flowcode",
        cli: AppProviderCli.claude,
        name: "E-FlowCode",
        websiteUrl: "https://e-flowcode.cc",
        apiKeyUrl: "https://e-flowcode.cc",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://e-flowcode.cc",
        defaultModel: "",
        icon: "eflowcode",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://e-flowcode.cc"],
        config: {
          "env": {
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_BASE_URL": "https://e-flowcode.cc",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "lionccapi",
      label: "LionCCAPI",
      template: AppProviderConfig(
        id: "lionccapi",
        cli: AppProviderCli.claude,
        name: "LionCCAPI",
        websiteUrl: "https://vibecodingapi.ai",
        apiKeyUrl: "",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://vibecodingapi.ai",
        defaultModel: "",
        icon: "lioncc",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "lionccapi",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://vibecodingapi.ai",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "openrouter",
      label: "OpenRouter",
      template: AppProviderConfig(
        id: "openrouter",
        cli: AppProviderCli.claude,
        name: "OpenRouter",
        websiteUrl: "https://openrouter.ai",
        apiKeyUrl: "https://openrouter.ai/keys",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://openrouter.ai/api",
        defaultModel: "anthropic/claude-sonnet-4.6",
        icon: "openrouter",
        iconColor: "#6566F1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://openrouter.ai/api",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "anthropic/claude-sonnet-4.6",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "anthropic/claude-haiku-4.5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "anthropic/claude-sonnet-4.6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "anthropic/claude-opus-4.7",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "therouter",
      label: "TheRouter",
      template: AppProviderConfig(
        id: "therouter",
        cli: AppProviderCli.claude,
        name: "TheRouter",
        websiteUrl: "https://therouter.ai",
        apiKeyUrl: "https://dashboard.therouter.ai",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.therouter.ai",
        defaultModel: "anthropic/claude-sonnet-4.6",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.therouter.ai"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.therouter.ai",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_API_KEY": "",
            "ANTHROPIC_MODEL": "anthropic/claude-sonnet-4.6",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "anthropic/claude-haiku-4.5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "anthropic/claude-sonnet-4.6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "anthropic/claude-opus-4.7",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "novita-ai",
      label: "Novita AI",
      template: AppProviderConfig(
        id: "novita-ai",
        cli: AppProviderCli.claude,
        name: "Novita AI",
        websiteUrl: "https://novita.ai",
        apiKeyUrl: "https://novita.ai",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.novita.ai/anthropic",
        defaultModel: "zai-org/glm-5",
        icon: "novita",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.novita.ai/anthropic"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.novita.ai/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "zai-org/glm-5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "zai-org/glm-5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "zai-org/glm-5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "zai-org/glm-5",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "github-copilot",
      label: "GitHub Copilot",
      template: AppProviderConfig(
        id: "github-copilot",
        cli: AppProviderCli.claude,
        name: "GitHub Copilot",
        websiteUrl: "https://github.com/features/copilot",
        apiKeyUrl: "",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.githubcopilot.com",
        defaultModel: "claude-sonnet-4.6",
        icon: "github",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.githubcopilot.com",
            "ANTHROPIC_MODEL": "claude-sonnet-4.6",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "claude-haiku-4.5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "claude-sonnet-4.6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "claude-sonnet-4.6",
          },
          "apiFormat": "openai_chat",
          "providerType": "github_copilot",
          "requiresOAuth": true,
        },
      ),
    ),
    AppProviderPreset(
      id: "codex",
      label: "Codex",
      template: AppProviderConfig(
        id: "codex",
        cli: AppProviderCli.claude,
        name: "Codex",
        websiteUrl: "https://openai.com/chatgpt/pricing",
        apiKeyUrl: "",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://chatgpt.com/backend-api/codex",
        defaultModel: "gpt-5.4",
        icon: "openai",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://chatgpt.com/backend-api/codex",
            "ANTHROPIC_MODEL": "gpt-5.4",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "gpt-5.4-mini",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "gpt-5.4",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "gpt-5.4",
          },
          "apiFormat": "openai_responses",
          "providerType": "codex_oauth",
          "requiresOAuth": true,
        },
      ),
    ),
    AppProviderPreset(
      id: "lemondata",
      label: "LemonData",
      template: AppProviderConfig(
        id: "lemondata",
        cli: AppProviderCli.claude,
        name: "LemonData",
        websiteUrl: "https://lemondata.cc",
        apiKeyUrl: "https://lemondata.cc/r/FFX1ZDUP",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_API_KEY",
        baseUrl: "https://api.lemondata.cc",
        defaultModel: "",
        icon: "lemondata",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "lemondata",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.lemondata.cc",
            "ANTHROPIC_API_KEY": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "nvidia",
      label: "Nvidia",
      template: AppProviderConfig(
        id: "nvidia",
        cli: AppProviderCli.claude,
        name: "Nvidia",
        websiteUrl: "https://build.nvidia.com",
        apiKeyUrl: "https://build.nvidia.com/settings/api-keys",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://integrate.api.nvidia.com",
        defaultModel: "moonshotai/kimi-k2.5",
        icon: "nvidia",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://integrate.api.nvidia.com",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "moonshotai/kimi-k2.5",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "moonshotai/kimi-k2.5",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "moonshotai/kimi-k2.5",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "moonshotai/kimi-k2.5",
          },
          "apiFormat": "openai_chat",
        },
      ),
    ),
    AppProviderPreset(
      id: "pipellm",
      label: "PIPELLM",
      template: AppProviderConfig(
        id: "pipellm",
        cli: AppProviderCli.claude,
        name: "PIPELLM",
        websiteUrl: "https://code.pipellm.ai",
        apiKeyUrl: "https://code.pipellm.ai/login?ref=uvw650za",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://cc-api.pipellm.ai",
        defaultModel: "claude-opus-4-7",
        icon: "pipellm",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://cc-api.pipellm.ai",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "claude-opus-4-7",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "claude-haiku-4-5-20251001",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "claude-sonnet-4-6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "claude-opus-4-7",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "xiaomi-mimo",
      label: "Xiaomi MiMo",
      template: AppProviderConfig(
        id: "xiaomi-mimo",
        cli: AppProviderCli.claude,
        name: "Xiaomi MiMo",
        websiteUrl: "https://platform.xiaomimimo.com",
        apiKeyUrl: "https://platform.xiaomimimo.com/#/console/api-keys",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.xiaomimimo.com/anthropic",
        defaultModel: "mimo-v2-pro",
        icon: "xiaomimimo",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.xiaomimimo.com/anthropic",
            "ANTHROPIC_AUTH_TOKEN": "",
            "ANTHROPIC_MODEL": "mimo-v2-pro",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL": "mimo-v2-pro",
            "ANTHROPIC_DEFAULT_SONNET_MODEL": "mimo-v2-pro",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "mimo-v2-pro",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aws-bedrock-aksk",
      label: "AWS Bedrock (AKSK)",
      template: AppProviderConfig(
        id: "aws-bedrock-aksk",
        cli: AppProviderCli.claude,
        name: "AWS Bedrock (AKSK)",
        websiteUrl: "https://aws.amazon.com/bedrock/",
        apiKeyUrl: "",
        category: AppProviderCategory.cloudProvider,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://bedrock-runtime.\${AWS_REGION}.amazonaws.com",
        defaultModel: "global.anthropic.claude-opus-4-7",
        icon: "aws",
        iconColor: "#FF9900",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://bedrock-runtime.\${AWS_REGION}.amazonaws.com",
            "AWS_ACCESS_KEY_ID": "\${AWS_ACCESS_KEY_ID}",
            "AWS_SECRET_ACCESS_KEY": "\${AWS_SECRET_ACCESS_KEY}",
            "AWS_REGION": "\${AWS_REGION}",
            "ANTHROPIC_MODEL": "global.anthropic.claude-opus-4-7",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL":
                "global.anthropic.claude-haiku-4-5-20251001-v1:0",
            "ANTHROPIC_DEFAULT_SONNET_MODEL":
                "global.anthropic.claude-sonnet-4-6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "global.anthropic.claude-opus-4-7",
            "CLAUDE_CODE_USE_BEDROCK": "1",
          },
          "templateValues": {
            "AWS_REGION": {
              "label": "AWS Region",
              "placeholder": "us-west-2",
              "editorValue": "us-west-2",
            },
            "AWS_ACCESS_KEY_ID": {
              "label": "Access Key ID",
              "placeholder": "AKIA...",
              "editorValue": "",
            },
            "AWS_SECRET_ACCESS_KEY": {
              "label": "Secret Access Key",
              "placeholder": "your-secret-key",
              "editorValue": "",
            },
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aws-bedrock-api-key",
      label: "AWS Bedrock (API Key)",
      template: AppProviderConfig(
        id: "aws-bedrock-api-key",
        cli: AppProviderCli.claude,
        name: "AWS Bedrock (API Key)",
        websiteUrl: "https://aws.amazon.com/bedrock/",
        apiKeyUrl: "",
        category: AppProviderCategory.cloudProvider,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://bedrock-runtime.\${AWS_REGION}.amazonaws.com",
        defaultModel: "global.anthropic.claude-opus-4-7",
        icon: "aws",
        iconColor: "#FF9900",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL":
                "https://bedrock-runtime.\${AWS_REGION}.amazonaws.com",
            "AWS_REGION": "\${AWS_REGION}",
            "ANTHROPIC_MODEL": "global.anthropic.claude-opus-4-7",
            "ANTHROPIC_DEFAULT_HAIKU_MODEL":
                "global.anthropic.claude-haiku-4-5-20251001-v1:0",
            "ANTHROPIC_DEFAULT_SONNET_MODEL":
                "global.anthropic.claude-sonnet-4-6",
            "ANTHROPIC_DEFAULT_OPUS_MODEL": "global.anthropic.claude-opus-4-7",
            "CLAUDE_CODE_USE_BEDROCK": "1",
          },
          "templateValues": {
            "AWS_REGION": {
              "label": "AWS Region",
              "placeholder": "us-west-2",
              "editorValue": "us-west-2",
            },
          },
        },
      ),
    ),
  ];

  static AppProviderPreset? byId(String id) {
    for (final preset in all) {
      if (preset.id == id) return preset;
    }
    return null;
  }
}
