import '../app_provider_config.dart';

/// Claude CLI provider presets (part 3 of 4). Aggregated by [ClaudeProviderPresets].
const List<AppProviderPreset> claudeProviderPresetsPart3 = <AppProviderPreset>[
    AppProviderPreset(
      id: "claudeapi",
      label: "ClaudeAPI",
      template: AppProviderConfig(
        id: "claudeapi",
        cli: CliTool.claude,
        name: "ClaudeAPI",
        websiteUrl: "https://claudeapi.com",
        apiKeyUrl: "https://console.claudeapi.com/register?aff=pCLD",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://gw.claudeapi.com",
        defaultModel: "",
        icon: "claudeapi",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "claudeapi",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://gw.claudeapi.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "claudecn",
      label: "ClaudeCN",
      template: AppProviderConfig(
        id: "claudecn",
        cli: CliTool.claude,
        name: "ClaudeCN",
        websiteUrl: "https://claudecn.top",
        apiKeyUrl: "https://claudecn.top/register?aff=ccswitch",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://claudecn.top",
        defaultModel: "",
        icon: "claudecn",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "claudecn",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://claudecn.top",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "runapi",
      label: "RunAPI",
      template: AppProviderConfig(
        id: "runapi",
        cli: CliTool.claude,
        name: "RunAPI",
        websiteUrl: "https://runapi.co",
        apiKeyUrl: "https://runapi.co",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://runapi.co",
        defaultModel: "",
        icon: "runapi",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "runapi",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://runapi.co",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "relaxycode",
      label: "RelaxyCode",
      template: AppProviderConfig(
        id: "relaxycode",
        cli: CliTool.claude,
        name: "RelaxyCode",
        websiteUrl: "https://www.relaxycode.com",
        apiKeyUrl: "https://www.relaxycode.com/register",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.relaxycode.com",
        defaultModel: "",
        icon: "relaxcode",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://www.relaxycode.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "cubence",
      label: "Cubence",
      template: AppProviderConfig(
        id: "cubence",
        cli: CliTool.claude,
        name: "Cubence",
        websiteUrl: "https://cubence.com",
        apiKeyUrl: "https://cubence.com/signup?code=CCSWITCH&source=ccs",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.cubence.com",
        defaultModel: "",
        icon: "cubence",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "cubence",
        endpointCandidates: [
          "https://api.cubence.com",
          "https://api-cf.cubence.com",
          "https://api-dmit.cubence.com",
          "https://api-bwg.cubence.com",
        ],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.cubence.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aigocode",
      label: "AIGoCode",
      template: AppProviderConfig(
        id: "aigocode",
        cli: CliTool.claude,
        name: "AIGoCode",
        websiteUrl: "https://aigocode.com",
        apiKeyUrl: "https://aigocode.com/invite/CC-SWITCH",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.aigocode.com",
        defaultModel: "",
        icon: "aigocode",
        iconColor: "#5B7FFF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aigocode",
        endpointCandidates: ["https://api.aigocode.com"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.aigocode.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "rightcode",
      label: "RightCode",
      template: AppProviderConfig(
        id: "rightcode",
        cli: CliTool.claude,
        name: "RightCode",
        websiteUrl: "https://www.right.codes",
        apiKeyUrl: "https://www.right.codes/register?aff=CCSWITCH",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.right.codes/claude",
        defaultModel: "",
        icon: "rc",
        iconColor: "#E96B2C",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "rightcode",
        endpointCandidates: [],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://www.right.codes/claude",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aicodemirror",
      label: "AICodeMirror",
      template: AppProviderConfig(
        id: "aicodemirror",
        cli: CliTool.claude,
        name: "AICodeMirror",
        websiteUrl: "https://www.aicodemirror.com",
        apiKeyUrl: "https://www.aicodemirror.com/register?invitecode=9915W3",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.aicodemirror.com/api/claudecode",
        defaultModel: "",
        icon: "aicodemirror",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aicodemirror",
        endpointCandidates: [
          "https://api.aicodemirror.com/api/claudecode",
          "https://api.claudecode.net.cn/api/claudecode",
        ],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.aicodemirror.com/api/claudecode",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "aicoding",
      label: "AICoding",
      template: AppProviderConfig(
        id: "aicoding",
        cli: CliTool.claude,
        name: "AICoding",
        websiteUrl: "https://aicoding.sh",
        apiKeyUrl: "https://aicoding.sh/i/CCSWITCH",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.aicoding.sh",
        defaultModel: "",
        icon: "aicoding",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aicoding",
        endpointCandidates: ["https://api.aicoding.sh"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.aicoding.sh",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "crazyrouter",
      label: "CrazyRouter",
      template: AppProviderConfig(
        id: "crazyrouter",
        cli: CliTool.claude,
        name: "CrazyRouter",
        websiteUrl: "https://www.crazyrouter.com",
        apiKeyUrl:
            "https://www.crazyrouter.com/register?aff=OZcm&ref=cc-switch",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://cn.crazyrouter.com",
        defaultModel: "",
        icon: "crazyrouter",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "crazyrouter",
        endpointCandidates: ["https://cn.crazyrouter.com"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://cn.crazyrouter.com",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "sssaicode",
      label: "SSSAiCode",
      template: AppProviderConfig(
        id: "sssaicode",
        cli: CliTool.claude,
        name: "SSSAiCode",
        websiteUrl: "https://www.sssaicode.com",
        apiKeyUrl: "https://www.sssaicode.com/register?ref=DCP0SM",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://node-hk.sssaicode.com/api",
        defaultModel: "",
        icon: "sssaicode",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "sssaicode",
        endpointCandidates: [
          "https://node-hk.sssaicode.com/api",
          "https://claude2.sssaicode.com/api",
          "https://anti.sssaicode.com/api",
        ],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://node-hk.sssaicode.com/api",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "compshare",
      label: "Compshare",
      template: AppProviderConfig(
        id: "compshare",
        cli: CliTool.claude,
        name: "Compshare",
        websiteUrl: "https://www.compshare.cn",
        apiKeyUrl:
            "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.modelverse.cn",
        defaultModel: "",
        icon: "ucloud",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ucloud",
        endpointCandidates: ["https://api.modelverse.cn"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://api.modelverse.cn",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "compshare-coding-plan",
      label: "Compshare Coding Plan",
      template: AppProviderConfig(
        id: "compshare-coding-plan",
        cli: CliTool.claude,
        name: "Compshare Coding Plan",
        websiteUrl: "https://www.compshare.cn",
        apiKeyUrl:
            "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://cp.compshare.cn",
        defaultModel: "",
        icon: "ucloud",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ucloud",
        endpointCandidates: ["https://cp.compshare.cn"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://cp.compshare.cn",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
    AppProviderPreset(
      id: "micu",
      label: "Micu",
      template: AppProviderConfig(
        id: "micu",
        cli: CliTool.claude,
        name: "Micu",
        websiteUrl: "https://www.micuapi.ai",
        apiKeyUrl: "https://www.micuapi.ai/register?aff=aOYQ",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.micuapi.ai",
        defaultModel: "",
        icon: "micu",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "micu",
        endpointCandidates: ["https://www.micuapi.ai"],
        config: {
          "env": {
            "ANTHROPIC_BASE_URL": "https://www.micuapi.ai",
            "ANTHROPIC_AUTH_TOKEN": "",
          },
        },
      ),
    ),
];
