import '../app_provider_config.dart';

/// Claude CLI provider presets (part 2 of 4). Aggregated by [ClaudeProviderPresets].
const List<AppProviderPreset> claudeProviderPresetsPart2 = <AppProviderPreset>[
    AppProviderPreset(
      id: "kimi-for-coding",
      label: "Kimi For Coding",
      template: AppProviderConfig(
        id: "kimi-for-coding",
        cli: CliTool.claude,
        name: "Kimi For Coding",
        websiteUrl: "https://www.kimi.com/code/docs/",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.kimi.com/coding/",
        defaultModel: "",
        icon: "kimi",
        iconColor: "#6366F1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "stepfun",
      label: "StepFun",
      template: AppProviderConfig(
        id: "stepfun",
        cli: CliTool.claude,
        name: "StepFun",
        websiteUrl: "https://platform.stepfun.com/step-plan",
        apiKeyUrl: "https://platform.stepfun.com/interface-key",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.stepfun.com/step_plan",
        defaultModel: "step-3.5-flash-2603",
        icon: "stepfun",
        iconColor: "#16D6D2",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.stepfun.com/step_plan"],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "stepfun-en",
      label: "StepFun en",
      template: AppProviderConfig(
        id: "stepfun-en",
        cli: CliTool.claude,
        name: "StepFun en",
        websiteUrl: "https://platform.stepfun.ai/step-plan",
        apiKeyUrl: "https://platform.stepfun.ai/interface-key",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.stepfun.ai/step_plan",
        defaultModel: "step-3.5-flash-2603",
        icon: "stepfun",
        iconColor: "#16D6D2",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.stepfun.ai/step_plan"],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "modelscope",
      label: "ModelScope",
      template: AppProviderConfig(
        id: "modelscope",
        cli: CliTool.claude,
        name: "ModelScope",
        websiteUrl: "https://modelscope.cn",
        apiKeyUrl: "",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api-inference.modelscope.cn",
        defaultModel: "ZhipuAI/GLM-5",
        icon: "modelscope",
        iconColor: "#624AFF",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "kat-coder",
      label: "KAT-Coder",
      template: AppProviderConfig(
        id: "kat-coder",
        cli: CliTool.claude,
        name: "KAT-Coder",
        websiteUrl: "https://console.streamlake.ai",
        apiKeyUrl: "https://console.streamlake.ai/console/api-key",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl:
            "https://vanchin.streamlake.ai/api/gateway/v1/endpoints/\${ENDPOINT_ID}/claude-code-proxy",
        defaultModel: "KAT-Coder-Pro V1",
        icon: "catcoder",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "models": {
            "KAT-Coder-Pro V1": {"name": "KAT-Coder-Pro V1", "model": "KAT-Coder-Pro V1", "enabled": true},
            "KAT-Coder-Air V1": {"name": "KAT-Coder-Air V1", "model": "KAT-Coder-Air V1", "enabled": true, "role": "background"},
          },
          "templateValues": {
            "ENDPOINT_ID": {
              "label": "Vanchin Endpoint ID",
              "placeholder": "ep-xxx-xxx",
              "defaultValue": "",
              "editorValue": "",
            },
          },
        }
      ),
    ),
    AppProviderPreset(
      id: "longcat",
      label: "Longcat",
      template: AppProviderConfig(
        id: "longcat",
        cli: CliTool.claude,
        name: "Longcat",
        websiteUrl: "https://longcat.chat/platform",
        apiKeyUrl: "https://longcat.chat/platform/api_keys",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.longcat.chat/anthropic",
        defaultModel: "LongCat-Flash-Chat",
        icon: "longcat",
        iconColor: "#29E154",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "env": {
            "CLAUDE_CODE_MAX_OUTPUT_TOKENS": "6000",
          },
        }
      ),
    ),
    AppProviderPreset(
      id: "minimax",
      label: "MiniMax",
      template: AppProviderConfig(
        id: "minimax",
        cli: CliTool.claude,
        name: "MiniMax",
        websiteUrl: "https://platform.minimaxi.com",
        apiKeyUrl: "https://platform.minimaxi.com/subscribe/coding-plan",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.minimaxi.com/anthropic",
        defaultModel: "MiniMax-M2.7",
        icon: "minimax",
        iconColor: "#FF6B6B",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "minimax_cn",
        endpointCandidates: [],
        config: {
          "env": {
            "API_TIMEOUT_MS": "3000000",
          },
        }
      ),
    ),
    AppProviderPreset(
      id: "minimax-en",
      label: "MiniMax en",
      template: AppProviderConfig(
        id: "minimax-en",
        cli: CliTool.claude,
        name: "MiniMax en",
        websiteUrl: "https://platform.minimax.io",
        apiKeyUrl: "https://platform.minimax.io/subscribe/coding-plan",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.minimax.io/anthropic",
        defaultModel: "MiniMax-M2.7",
        icon: "minimax",
        iconColor: "#FF6B6B",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "minimax_en",
        endpointCandidates: [],
        config: {
          "env": {
            "API_TIMEOUT_MS": "3000000",
          },
        }
      ),
    ),
    AppProviderPreset(
      id: "bailing",
      label: "BaiLing",
      template: AppProviderConfig(
        id: "bailing",
        cli: CliTool.claude,
        name: "BaiLing",
        websiteUrl: "https://alipaytbox.yuque.com/sxs0ba/ling/get_started",
        apiKeyUrl: "",
        category: AppProviderCategory.cnOfficial,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.tbox.cn/api/anthropic",
        defaultModel: "Ling-2.5-1T",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "aihubmix",
      label: "AiHubMix",
      template: AppProviderConfig(
        id: "aihubmix",
        cli: CliTool.claude,
        name: "AiHubMix",
        websiteUrl: "https://aihubmix.com",
        apiKeyUrl: "https://aihubmix.com",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_API_KEY",
        baseUrl: "https://aihubmix.com",
        defaultModel: "",
        icon: "aihubmix",
        iconColor: "#006FFB",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [
          "https://aihubmix.com",
          "https://api.aihubmix.com",
        ],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "siliconflow",
      label: "SiliconFlow",
      template: AppProviderConfig(
        id: "siliconflow",
        cli: CliTool.claude,
        name: "SiliconFlow",
        websiteUrl: "https://siliconflow.cn",
        apiKeyUrl: "https://cloud.siliconflow.cn/i/drGuwc9k",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.siliconflow.cn",
        defaultModel: "Pro/MiniMaxAI/MiniMax-M2.7",
        icon: "siliconflow",
        iconColor: "#6E29F6",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "siliconflow",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "siliconflow-en",
      label: "SiliconFlow en",
      template: AppProviderConfig(
        id: "siliconflow-en",
        cli: CliTool.claude,
        name: "SiliconFlow en",
        websiteUrl: "https://siliconflow.com",
        apiKeyUrl: "https://cloud.siliconflow.cn/i/drGuwc9k",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://api.siliconflow.com",
        defaultModel: "MiniMaxAI/MiniMax-M2.7",
        icon: "siliconflow",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "siliconflow",
        endpointCandidates: [],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "dmxapi",
      label: "DMXAPI",
      template: AppProviderConfig(
        id: "dmxapi",
        cli: CliTool.claude,
        name: "DMXAPI",
        websiteUrl: "https://www.dmxapi.cn",
        apiKeyUrl: "https://www.dmxapi.cn",
        category: AppProviderCategory.aggregator,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.dmxapi.cn",
        defaultModel: "",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "dmxapi",
        endpointCandidates: ["https://www.dmxapi.cn", "https://api.dmxapi.cn"],
        config: {}
      ),
    ),
    AppProviderPreset(
      id: "packycode",
      label: "PackyCode",
      template: AppProviderConfig(
        id: "packycode",
        cli: CliTool.claude,
        name: "PackyCode",
        websiteUrl: "https://www.packyapi.com",
        apiKeyUrl: "https://www.packyapi.com/register?aff=cc-switch",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "ANTHROPIC_AUTH_TOKEN",
        baseUrl: "https://www.packyapi.com",
        defaultModel: "",
        icon: "packycode",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "packycode",
        endpointCandidates: [
          "https://www.packyapi.com",
          "https://api-slb.packyapi.com",
        ],
        config: {}
      ),
    ),
];
