import '../app_provider_config.dart';

class CodexProviderPresets {
  const CodexProviderPresets._();

  static const all = <AppProviderPreset>[
    AppProviderPreset(
      id: "openai-official",
      label: "OpenAI Official",
      template: AppProviderConfig(
        id: "openai-official",
        cli: AppProviderCli.codex,
        name: "OpenAI Official",
        websiteUrl: "https://chatgpt.com/codex",
        apiKeyUrl: "",
        category: AppProviderCategory.official,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "",
        defaultModel: "",
        icon: "openai",
        iconColor: "#00A67E",
        isOfficial: true,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {"auth": {}, "configToml": ""},
      ),
    ),
    AppProviderPreset(
      id: "shengsuanyun",
      label: "Shengsuanyun",
      template: AppProviderConfig(
        id: "shengsuanyun",
        cli: AppProviderCli.codex,
        name: "Shengsuanyun",
        websiteUrl: "https://www.shengsuanyun.com",
        apiKeyUrl: "https://www.shengsuanyun.com/?from=CH_4HHXMRYF",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://router.shengsuanyun.com/api/v1",
        defaultModel: "gpt-5.4",
        icon: "shengsuanyun",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "shengsuanyun",
        endpointCandidates: [],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"shengsuanyun\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.shengsuanyun]\nname = \"shengsuanyun\"\nbase_url = \"https://router.shengsuanyun.com/api/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "patewayai",
      label: "PatewayAI",
      template: AppProviderConfig(
        id: "patewayai",
        cli: AppProviderCli.codex,
        name: "PatewayAI",
        websiteUrl: "https://pateway.ai",
        apiKeyUrl: "https://pateway.ai/?ch=etzpm8&aff=WB6M6F67#/",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.pateway.ai/v1",
        defaultModel: "gpt-5.5",
        icon: "pateway",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "patewayai",
        endpointCandidates: ["https://api.pateway.ai/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"patewayai\"\nmodel = \"gpt-5.5\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.patewayai]\nname = \"patewayai\"\nbase_url = \"https://api.pateway.ai/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "azure-openai",
      label: "Azure OpenAI",
      template: AppProviderConfig(
        id: "azure-openai",
        cli: AppProviderCli.codex,
        name: "Azure OpenAI",
        websiteUrl:
            "https://learn.microsoft.com/en-us/azure/ai-foundry/openai/how-to/codex",
        apiKeyUrl: "",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://YOUR_RESOURCE_NAME.openai.azure.com/openai",
        defaultModel: "gpt-5.4",
        icon: "azure",
        iconColor: "#0078D4",
        isOfficial: true,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [
          "https://YOUR_RESOURCE_NAME.openai.azure.com/openai",
        ],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"azure\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.azure]\nname = \"Azure OpenAI\"\nbase_url = \"https://YOUR_RESOURCE_NAME.openai.azure.com/openai\"\nenv_key = \"OPENAI_API_KEY\"\nquery_params = { \"api-version\" = \"2025-04-01-preview\" }\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "aihubmix",
      label: "AiHubMix",
      template: AppProviderConfig(
        id: "aihubmix",
        cli: AppProviderCli.codex,
        name: "AiHubMix",
        websiteUrl: "https://aihubmix.com",
        apiKeyUrl: "",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://aihubmix.com/v1",
        defaultModel: "gpt-5.4",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [
          "https://aihubmix.com/v1",
          "https://api.aihubmix.com/v1",
        ],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"aihubmix\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.aihubmix]\nname = \"aihubmix\"\nbase_url = \"https://aihubmix.com/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "dmxapi",
      label: "DMXAPI",
      template: AppProviderConfig(
        id: "dmxapi",
        cli: AppProviderCli.codex,
        name: "DMXAPI",
        websiteUrl: "https://www.dmxapi.cn",
        apiKeyUrl: "",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://www.dmxapi.cn/v1",
        defaultModel: "gpt-5.4",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "dmxapi",
        endpointCandidates: ["https://www.dmxapi.cn/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"dmxapi\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.dmxapi]\nname = \"dmxapi\"\nbase_url = \"https://www.dmxapi.cn/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "packycode",
      label: "PackyCode",
      template: AppProviderConfig(
        id: "packycode",
        cli: AppProviderCli.codex,
        name: "PackyCode",
        websiteUrl: "https://www.packyapi.com",
        apiKeyUrl: "https://www.packyapi.com/register?aff=cc-switch",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://www.packyapi.com/v1",
        defaultModel: "gpt-5.4",
        icon: "packycode",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "packycode",
        endpointCandidates: [
          "https://www.packyapi.com/v1",
          "https://api-slb.packyapi.com/v1",
        ],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"packycode\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.packycode]\nname = \"packycode\"\nbase_url = \"https://www.packyapi.com/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "claudecn",
      label: "ClaudeCN",
      template: AppProviderConfig(
        id: "claudecn",
        cli: AppProviderCli.codex,
        name: "ClaudeCN",
        websiteUrl: "https://claudecn.top",
        apiKeyUrl: "https://claudecn.top/register?aff=ccswitch",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://claudecn.top/v1",
        defaultModel: "gpt-5.5",
        icon: "claudecn",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "claudecn",
        endpointCandidates: [],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"claudecn\"\nmodel = \"gpt-5.5\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.claudecn]\nname = \"claudecn\"\nbase_url = \"https://claudecn.top/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "runapi",
      label: "RunAPI",
      template: AppProviderConfig(
        id: "runapi",
        cli: AppProviderCli.codex,
        name: "RunAPI",
        websiteUrl: "https://runapi.co",
        apiKeyUrl: "https://runapi.co",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://runapi.co/v1",
        defaultModel: "gpt-5.5",
        icon: "runapi",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "runapi",
        endpointCandidates: [],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"runapi\"\nmodel = \"gpt-5.5\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.runapi]\nname = \"runapi\"\nbase_url = \"https://runapi.co/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "relaxycode",
      label: "RelaxyCode",
      template: AppProviderConfig(
        id: "relaxycode",
        cli: AppProviderCli.codex,
        name: "RelaxyCode",
        websiteUrl: "https://www.relaxycode.com",
        apiKeyUrl: "https://www.relaxycode.com/register",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://www.relaxycode.com/v1",
        defaultModel: "gpt-5.5",
        icon: "relaxcode",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"relaxycode\"\nmodel = \"gpt-5.5\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.relaxycode]\nname = \"relaxycode\"\nbase_url = \"https://www.relaxycode.com/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "cubence",
      label: "Cubence",
      template: AppProviderConfig(
        id: "cubence",
        cli: AppProviderCli.codex,
        name: "Cubence",
        websiteUrl: "https://cubence.com",
        apiKeyUrl: "https://cubence.com/signup?code=CCSWITCH&source=ccs",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.cubence.com/v1",
        defaultModel: "gpt-5.4",
        icon: "cubence",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "cubence",
        endpointCandidates: [
          "https://api.cubence.com/v1",
          "https://api-cf.cubence.com/v1",
          "https://api-dmit.cubence.com/v1",
          "https://api-bwg.cubence.com/v1",
        ],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"cubence\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.cubence]\nname = \"cubence\"\nbase_url = \"https://api.cubence.com/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "aigocode",
      label: "AIGoCode",
      template: AppProviderConfig(
        id: "aigocode",
        cli: AppProviderCli.codex,
        name: "AIGoCode",
        websiteUrl: "https://aigocode.com",
        apiKeyUrl: "https://aigocode.com/invite/CC-SWITCH",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.aigocode.com",
        defaultModel: "gpt-5.4",
        icon: "aigocode",
        iconColor: "#5B7FFF",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aigocode",
        endpointCandidates: ["https://api.aigocode.com"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"aigocode\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.aigocode]\nname = \"aigocode\"\nbase_url = \"https://api.aigocode.com\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "rightcode",
      label: "RightCode",
      template: AppProviderConfig(
        id: "rightcode",
        cli: AppProviderCli.codex,
        name: "RightCode",
        websiteUrl: "https://www.right.codes",
        apiKeyUrl: "https://www.right.codes/register?aff=CCSWITCH",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://right.codes/codex/v1",
        defaultModel: "gpt-5.4",
        icon: "rc",
        iconColor: "#E96B2C",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "rightcode",
        endpointCandidates: [],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"rightcode\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.rightcode]\nname = \"rightcode\"\nbase_url = \"https://right.codes/codex/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "aicodemirror",
      label: "AICodeMirror",
      template: AppProviderConfig(
        id: "aicodemirror",
        cli: AppProviderCli.codex,
        name: "AICodeMirror",
        websiteUrl: "https://www.aicodemirror.com",
        apiKeyUrl: "https://www.aicodemirror.com/register?invitecode=9915W3",
        category: AppProviderCategory.custom,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.aicodemirror.com/api/codex/backend-api/codex",
        defaultModel: "gpt-5.4",
        icon: "aicodemirror",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aicodemirror",
        endpointCandidates: [
          "https://api.aicodemirror.com/api/codex/backend-api/codex",
          "https://api.claudecode.net.cn/api/codex/backend-api/codex",
        ],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"aicodemirror\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.aicodemirror]\nname = \"aicodemirror\"\nbase_url = \"https://api.aicodemirror.com/api/codex/backend-api/codex\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "aicoding",
      label: "AICoding",
      template: AppProviderConfig(
        id: "aicoding",
        cli: AppProviderCli.codex,
        name: "AICoding",
        websiteUrl: "https://aicoding.sh",
        apiKeyUrl: "https://aicoding.sh/i/CCSWITCH",
        category: AppProviderCategory.custom,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.aicoding.sh",
        defaultModel: "gpt-5.4",
        icon: "aicoding",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "aicoding",
        endpointCandidates: ["https://api.aicoding.sh"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"aicoding\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.aicoding]\nname = \"aicoding\"\nbase_url = \"https://api.aicoding.sh\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "crazyrouter",
      label: "CrazyRouter",
      template: AppProviderConfig(
        id: "crazyrouter",
        cli: AppProviderCli.codex,
        name: "CrazyRouter",
        websiteUrl: "https://www.crazyrouter.com",
        apiKeyUrl:
            "https://www.crazyrouter.com/register?aff=OZcm&ref=cc-switch",
        category: AppProviderCategory.custom,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://cn.crazyrouter.com/v1",
        defaultModel: "gpt-5.4",
        icon: "crazyrouter",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "crazyrouter",
        endpointCandidates: ["https://cn.crazyrouter.com/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"crazyrouter\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.crazyrouter]\nname = \"crazyrouter\"\nbase_url = \"https://cn.crazyrouter.com/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "sssaicode",
      label: "SSSAiCode",
      template: AppProviderConfig(
        id: "sssaicode",
        cli: AppProviderCli.codex,
        name: "SSSAiCode",
        websiteUrl: "https://www.sssaicode.com",
        apiKeyUrl: "https://www.sssaicode.com/register?ref=DCP0SM",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://node-hk.sssaicode.com/api/v1",
        defaultModel: "gpt-5.4",
        icon: "sssaicode",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "sssaicode",
        endpointCandidates: [
          "https://node-hk.sssaicode.com/api/v1",
          "https://claude2.sssaicode.com/api/v1",
          "https://anti.sssaicode.com/api/v1",
        ],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"sssaicode\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.sssaicode]\nname = \"sssaicode\"\nbase_url = \"https://node-hk.sssaicode.com/api/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "compshare",
      label: "Compshare",
      template: AppProviderConfig(
        id: "compshare",
        cli: AppProviderCli.codex,
        name: "Compshare",
        websiteUrl: "https://www.compshare.cn",
        apiKeyUrl:
            "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.modelverse.cn/v1",
        defaultModel: "gpt-5.4",
        icon: "ucloud",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ucloud",
        endpointCandidates: ["https://api.modelverse.cn/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"compshare\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.compshare]\nname = \"compshare\"\nbase_url = \"https://api.modelverse.cn/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "compshare-coding-plan",
      label: "Compshare Coding Plan",
      template: AppProviderConfig(
        id: "compshare-coding-plan",
        cli: AppProviderCli.codex,
        name: "Compshare Coding Plan",
        websiteUrl: "https://www.compshare.cn",
        apiKeyUrl:
            "https://www.compshare.cn/coding-plan?ytag=GPU_YY_YX_git_cc-switch",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://cp.compshare.cn/v1",
        defaultModel: "gpt-5.4",
        icon: "ucloud",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ucloud",
        endpointCandidates: ["https://cp.compshare.cn/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"compshare_coding\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.compshare_coding]\nname = \"compshare_coding\"\nbase_url = \"https://cp.compshare.cn/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "micu",
      label: "Micu",
      template: AppProviderConfig(
        id: "micu",
        cli: AppProviderCli.codex,
        name: "Micu",
        websiteUrl: "https://www.micuapi.ai",
        apiKeyUrl: "https://www.micuapi.ai/register?aff=aOYQ",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://www.micuapi.ai/v1",
        defaultModel: "gpt-5.4",
        icon: "micu",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "micu",
        endpointCandidates: ["https://www.micuapi.ai/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"micu\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.micu]\nname = \"micu\"\nbase_url = \"https://www.micuapi.ai/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "ctok-ai",
      label: "CTok.ai",
      template: AppProviderConfig(
        id: "ctok-ai",
        cli: AppProviderCli.codex,
        name: "CTok.ai",
        websiteUrl: "https://ctok.ai",
        apiKeyUrl: "https://ctok.ai",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.ctok.ai/v1",
        defaultModel: "gpt-5.4",
        icon: "ctok",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "ctok",
        endpointCandidates: ["https://api.ctok.ai/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"ctok\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.ctok]\nname = \"ctok\"\nbase_url = \"https://api.ctok.ai/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "lionccapi",
      label: "LionCCAPI",
      template: AppProviderConfig(
        id: "lionccapi",
        cli: AppProviderCli.codex,
        name: "LionCCAPI",
        websiteUrl: "https://vibecodingapi.ai",
        apiKeyUrl: "",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://vibecodingapi.ai/v1",
        defaultModel: "gpt-5.4",
        icon: "lioncc",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "lionccapi",
        endpointCandidates: [],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"lionccapi\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.lionccapi]\nname = \"lionccapi\"\nbase_url = \"https://vibecodingapi.ai/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "e-flowcode",
      label: "E-FlowCode",
      template: AppProviderConfig(
        id: "e-flowcode",
        cli: AppProviderCli.codex,
        name: "E-FlowCode",
        websiteUrl: "https://e-flowcode.cc",
        apiKeyUrl: "https://e-flowcode.cc",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://e-flowcode.cc/v1",
        defaultModel: "gpt-5.4",
        icon: "eflowcode",
        iconColor: "#000000",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://e-flowcode.cc/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"e-flowcode\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\npersonality = \"pragmatic\"\n\n[model_providers.e-flowcode]\nname = \"e-flowcode\"\nbase_url = \"https://e-flowcode.cc/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true\nmodel_context_window = 1000000\nmodel_auto_compact_token_limit = 9000000",
        },
      ),
    ),
    AppProviderPreset(
      id: "lemondata",
      label: "LemonData",
      template: AppProviderConfig(
        id: "lemondata",
        cli: AppProviderCli.codex,
        name: "LemonData",
        websiteUrl: "https://lemondata.cc",
        apiKeyUrl: "https://lemondata.cc/r/FFX1ZDUP",
        category: AppProviderCategory.thirdParty,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.lemondata.cc/v1",
        defaultModel: "gpt-5.4",
        icon: "lemondata",
        iconColor: "",
        isOfficial: false,
        isPartner: true,
        partnerPromotionKey: "lemondata",
        endpointCandidates: ["https://api.lemondata.cc/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"lemondata\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.lemondata]\nname = \"lemondata\"\nbase_url = \"https://api.lemondata.cc/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "pipellm",
      label: "PIPELLM",
      template: AppProviderConfig(
        id: "pipellm",
        cli: AppProviderCli.codex,
        name: "PIPELLM",
        websiteUrl: "https://code.pipellm.ai",
        apiKeyUrl: "https://code.pipellm.ai/login?ref=uvw650za",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://cc-api.pipellm.ai/v1",
        defaultModel: "gpt-5.4",
        icon: "pipellm",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://cc-api.pipellm.ai/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"custom\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"medium\"\ndisable_response_storage = true\n\n[model_providers.custom]\nname = \"custom\"\nwire_api = \"responses\"\nrequires_openai_auth = true\nbase_url = \"https://cc-api.pipellm.ai/v1\"",
        },
      ),
    ),
    AppProviderPreset(
      id: "openrouter",
      label: "OpenRouter",
      template: AppProviderConfig(
        id: "openrouter",
        cli: AppProviderCli.codex,
        name: "OpenRouter",
        websiteUrl: "https://openrouter.ai",
        apiKeyUrl: "https://openrouter.ai/keys",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://openrouter.ai/api/v1",
        defaultModel: "gpt-5.4",
        icon: "openrouter",
        iconColor: "#6566F1",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: [],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"openrouter\"\nmodel = \"gpt-5.4\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.openrouter]\nname = \"openrouter\"\nbase_url = \"https://openrouter.ai/api/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
    AppProviderPreset(
      id: "therouter",
      label: "TheRouter",
      template: AppProviderConfig(
        id: "therouter",
        cli: AppProviderCli.codex,
        name: "TheRouter",
        websiteUrl: "https://therouter.ai",
        apiKeyUrl: "https://dashboard.therouter.ai",
        category: AppProviderCategory.aggregator,
        apiKeyField: "OPENAI_API_KEY",
        baseUrl: "https://api.therouter.ai/v1",
        defaultModel: "openai/gpt-5.3-codex",
        icon: "",
        iconColor: "",
        isOfficial: false,
        isPartner: false,
        partnerPromotionKey: "",
        endpointCandidates: ["https://api.therouter.ai/v1"],
        config: {
          "auth": {"OPENAI_API_KEY": ""},
          "configToml":
              "model_provider = \"therouter\"\nmodel = \"openai/gpt-5.3-codex\"\nmodel_reasoning_effort = \"high\"\ndisable_response_storage = true\n\n[model_providers.therouter]\nname = \"therouter\"\nbase_url = \"https://api.therouter.ai/v1\"\nwire_api = \"responses\"\nrequires_openai_auth = true",
        },
      ),
    ),
  ];

  static AppProviderPreset? byId(String id) {
    for (final preset in all) {
      if (preset.id == id) return preset;
    }
    return null;
  }
}
