/// Flutter Thread/Message/Part UI for ai_message_core.
library ai_message_ui;

export 'src/markdown/compiled_markdown_chrome.dart';
export 'src/ai_message_parts.dart';
export 'src/ai_message_view.dart';
export 'src/ai_thread.dart';
export 'src/history_render_scope.dart';
export 'src/message_action_bar.dart';
export 'src/message_streaming_scope.dart';
export 'src/part_grouping.dart';
export 'src/part_registry.dart';
export 'src/parts/chain_of_thought_view.dart';
export 'src/parts/expandable_tool_card.dart';
export 'src/parts/fade_expand_body.dart';
export 'src/parts/reasoning_part_view.dart';
export 'src/parts/text_part_view.dart';
export 'src/parts/subagent_preview_scaffold.dart';
export 'src/parts/tool_call_part_view.dart';
export 'src/parts/tool_group_view.dart';
export 'src/selection_dead_zone.dart';
export 'src/selection_height_style.dart';
export 'src/strings.dart';
export 'src/edit/edit_line_highlighter.dart';
export 'src/edit/edit_tool_card.dart' show EditToolCard, previewEditHunkLines;
export 'src/tool_call_bubble_scope.dart';
export 'src/tool_call_fold_scope.dart';
export 'src/markdown_link_actions.dart';
export 'src/tool_file_actions.dart';
export 'src/tool_subagent_actions.dart';
export 'src/theme.dart';
export 'src/thread_turns.dart';
export 'src/turn_height_cache.dart';
export 'src/turn_mount_keep_alive.dart';
export 'src/frozen_size.dart';
export 'src/virtual_thread_viewport.dart';
