import '../../../agent_status/member_agent_status_endpoint.dart';
import '../../registry/config_profile/agent_status_hooks.dart';

/// Pure builders for cursor agent-status hooks under the member fake HOME
/// `~/.cursor/hooks.json`.
///
/// Cursor's hooks are configured as `{"version": 1, "hooks": {<event>: [...]}}`
/// and each hook command receives the hook payload on stdin. We forward that
/// payload to the seat `/agent-status` endpoint so the normalized attention
/// (`working` / `done`) is driven by real tool lifecycle instead of only OSC
/// titles. Waiting stays on the title path.
abstract final class CursorHomeAgentStatusOverlay {
  CursorHomeAgentStatusOverlay._();

  /// Cursor hook events that carry tool / turn lifecycle signals.
  static const List<String> statusEvents = [
    'preToolUse',
    'postToolUse',
    'postToolUseFailure',
    'beforeSubmitPrompt',
    'afterAgentResponse',
    'stop',
  ];

  /// File name for one event's forwarding script (`.sh`; cursor hooks run bash).
  static String scriptFileName(String event) =>
      'teampilot-agent-status-$event.sh';

  /// Bash script that POSTs the hook stdin payload to the per-event
  /// `/agent-status` URL. Best-effort, never blocks the hook.
  static String scriptFor({
    required MemberAgentStatusEndpoint endpoint,
    required String memberId,
    required String event,
  }) {
    final url = agentStatusHookUrl(endpoint.url, event);
    final headerArgs = endpoint
        .headersFor(memberId)
        .entries
        .map((e) => "-H '${e.key}: ${e.value}'")
        .join(' ');
    return '''
#!/usr/bin/env bash
# Generated by TeamPilot — cursor agent-status hook ($event). Do not edit.
set -u
payload="\$(cat)"
if [ -z "\$payload" ]; then exit 0; fi
curl -sS -X POST '$url' $headerArgs -H 'Content-Type: application/json' -d "\$payload" >/dev/null 2>&1 || true
exit 0
''';
  }

  /// Merges agent-status hook entries into an existing hooks.json map,
  /// preserving existing entries (e.g. the bus `stop` hook written by
  /// [CursorHomeBusOverlay]).
  static Map<String, Object?> mergeHooksConfig(
    Map<String, Object?> existing, {
    required String Function(String event) scriptPathFor,
  }) {
    final hooks = Map<String, Object?>.from(
      (existing['hooks'] as Map?)?.cast<String, Object?>() ?? const {},
    );
    for (final event in statusEvents) {
      final command = "bash '${scriptPathFor(event)}'";
      final entries = List<Object?>.from((hooks[event] as List?) ?? const []);
      if (!entries.any((e) => e is Map && e['command'] == command)) {
        entries.add({'command': command, 'loop_limit': null});
      }
      hooks[event] = entries;
    }
    return {...existing, 'version': 1, 'hooks': hooks};
  }
}
