// Generated file - do not edit
// Generated by native_splash_screen_cli

import native_splash_screen_macos

class DebugNativeSplashScreenConfiguration: NativeSplashScreenConfigurationProvider {

    // MARK: - Splash screen properties
    let windowWidth: Int = 1380
    let windowHeight: Int = 960

    // MARK: - Window Title
    let windowTitle: String = "TeamPilot"

    // MARK: - Animation control
    let withAnimation: Bool = false

    // MARK: - Image properties
    let imageFileName: String = "splash_screen_debug.png"
    let imageWidth: Int = 1380
    let imageHeight: Int = 960
}
