display_name: TeamPilot
description: FlashSky AI TeamPilot client
maintainer: hhoa <m45937494@gmail.com>
section: utility
priority: optional
homepage: https://github.com/hhoao/flashskyai-ui
icon: assets/icons/icon.png
depends:
  - libgtk-3-0
  - libglib2.0-0
  - libgdk-pixbuf-2.0-0
