import 'dart:convert';

import '../../team_bus/mcp/teammate_bus_mcp_config.dart';
import '../../team_bus/mcp/teammate_bus_mcp_handler.dart';

/// Pure builders for mixed-mode team-bus files under native `$HOME/.cursor/`.
///
/// Cursor CLI reads these from the fake HOME directly (not `--plugin-dir`):
///
///   `$HOME/.cursor/hooks.json`       stop hook (top-level, not hooks/hooks.json)
///   `$HOME/.cursor/hooks/idle.sh`    POST /idle, translate decision
///   `$HOME/.cursor/mcp.json`         teammate-bus MCP server
///   `$HOME/.cursor/rules/role.mdc`   alwaysApply member identity
///
/// The `stop` hook posts to the bus `/idle` endpoint and translates the bus's
/// `{"decision":"block",...}` reply into Cursor's `{"followup_message":...}`
/// schema (Cursor has no `decision:block`), keeping the member in its
/// `wait_for_message` loop ("never stand down"). Mirrors [CodexTeamBusOverlay].
abstract final class CursorHomeBusOverlay {
  CursorHomeBusOverlay._();

  /// `$HOME/.cursor/hooks.json`: fire [idleScriptPath] on `stop`. `loop_limit: null`
  /// disables Cursor's default 5-iteration cap so the bus loop never auto-ends.
  /// Invoked via `bash <path>` so it needs no executable bit (Filesystem has no
  /// chmod, and SFTP/SSH backends differ).
  static Map<String, Object?> hooksConfig({required String idleScriptPath}) => {
    'version': 1,
    'hooks': {
      'stop': [
        {'command': "bash '$idleScriptPath'", 'loop_limit': null},
      ],
    },
  };

  /// `$HOME/.cursor/mcp.json`: registers the teammate-bus MCP server so the
  /// member gets `wait_for_message`/`send_message`/….
  static String buildMcpJson({required String memberId, required int port}) {
    const encoder = JsonEncoder.withIndent('  ');
    return encoder.convert({
      'mcpServers': {
        teammateBusMcpServerName: teammateBusMcpServerConfig(
          endpoint: Uri.parse('http://127.0.0.1:$port/mcp'),
          memberId: memberId,
        ),
      },
    });
  }

  /// `$HOME/.cursor/hooks/idle.sh`: POST the bus `/idle` endpoint (member is now
  /// idle), then translate a `decision:block` reply into a `followup_message` so
  /// Cursor re-prompts the member to call `wait_for_message`. When the bus releases
  /// the member (idle fuse → `{}`), emit nothing and let the turn end.
  static String idleScript({required String memberId, required int port}) {
    final followup = jsonEncode({
      'followup_message': TeammateBusMcpHandler.stopRedirectReason,
    });
    return '''
#!/usr/bin/env bash
# Generated by TeamPilot — cursor team-bus stop hook. Do not edit.
set -u
# Drain the stop-hook stdin payload; we key off the bus reply, not the payload.
cat >/dev/null 2>&1 || true
resp="\$(curl -sS -X POST -H 'X-Member: $memberId' 'http://127.0.0.1:$port/idle' 2>/dev/null || true)"
case "\$resp" in
  *'"decision":"block"'*)
    printf '%s' '$followup'
    ;;
esac
exit 0
''';
  }

  /// Wraps the composed role prompt as an always-apply Cursor rule (`.mdc`).
  static String roleRule(String body) {
    final buffer = StringBuffer()
      ..writeln('---')
      ..writeln('alwaysApply: true')
      ..writeln('---')
      ..writeln();
    if (body.isNotEmpty) buffer.writeln(body);
    return buffer.toString();
  }

  static int? parseBusPort(String? idleUrl) {
    if (idleUrl == null || idleUrl.isEmpty) return null;
    final uri = Uri.tryParse(idleUrl);
    if (uri == null || !uri.hasPort) return null;
    return uri.port;
  }
}
