import 'dart:convert';

import '../../team_bus/mcp/teammate_bus_mcp_config.dart';
import '../../team_bus/mcp/teammate_bus_mcp_handler.dart';
import '../../team_bus/member_bus_idle_endpoint.dart';

/// Pure builders for mixed-mode team-bus files under native `$HOME/.cursor/`.
abstract final class CursorHomeBusOverlay {
  CursorHomeBusOverlay._();

  static Map<String, Object?> hooksConfig({required String idleScriptPath}) => {
    'version': 1,
    'hooks': {
      'stop': [
        {'command': "bash '$idleScriptPath'", 'loop_limit': null},
      ],
    },
  };

  static String buildMcpJson({
    required String memberId,
    required MemberBusIdleEndpoint idle,
  }) {
    final port = idle.port;
    if (port == null) {
      throw ArgumentError('idle endpoint has no port: ${idle.url}');
    }
    const encoder = JsonEncoder.withIndent('  ');
    final headers = <String, String>{
      teammateBusMcpMemberHeader: memberId,
      if (idle.isRemote) teammateBusTokenHeader: idle.token!,
    };
    return encoder.convert({
      'mcpServers': {
        teammateBusMcpServerName: {
          'type': 'http',
          'url': 'http://127.0.0.1:$port/mcp',
          'headers': headers,
        },
      },
    });
  }

  static String idleScript({
    required String memberId,
    required MemberBusIdleEndpoint idle,
  }) {
    final port = idle.port;
    if (port == null) {
      throw ArgumentError('idle endpoint has no port: ${idle.url}');
    }
    final followup = jsonEncode({
      'followup_message': TeammateBusMcpHandler.stopRedirectReason,
    });
    final headerArgs = idle.headersFor(memberId).entries
        .map((e) => "-H '${e.key}: ${e.value}'")
        .join(' ');
    return '''
#!/usr/bin/env bash
# Generated by TeamPilot — cursor team-bus stop hook. Do not edit.
set -u
cat >/dev/null 2>&1 || true
resp="\$(curl -sS -X POST $headerArgs 'http://127.0.0.1:$port/idle' 2>/dev/null || true)"
case "\$resp" in
  *'"decision":"block"'*)
    printf '%s' '$followup'
    ;;
esac
exit 0
''';
  }

  static String roleRule(String body) {
    final buffer = StringBuffer()
      ..writeln('---')
      ..writeln('alwaysApply: true')
      ..writeln('---')
      ..writeln();
    if (body.isNotEmpty) buffer.writeln(body);
    return buffer.toString();
  }
}
