import '../../../team_bus/mcp/teammate_bus_mcp_handler.dart';
import '../../../team_bus/member_bus_idle_endpoint.dart';

/// Bash Stop-hook script filename under the member flashskyai config dir.
const flashskyaiStopIdleScriptFileName = 'teammate-bus-stop-idle.sh';

/// FlashskyAI's in-process [HookRunner] treats HTTP 2xx Stop hooks as allow and
/// **ignores** `decision:block` in the body (unlike Claude's `executeStopHooks`
/// path, which parses JSON). Command hooks only block on **exit code 2**.
///
/// Generate a curl wrapper that POSTs `/idle` and exits 2 when the bus returns
/// `decision:block`, so mixed seats stay in the `wait_for_message` loop.
String flashskyaiStopIdleScript({
  required String memberId,
  required MemberBusIdleEndpoint idle,
}) {
  final headerArgs = idle
      .headersFor(memberId)
      .entries
      .map((e) => "-H '${e.key}: ${e.value}'")
      .join(' ');
  // Keep stderr one line — HookRunner surfaces it as Stop-hook feedback.
  final reason = TeammateBusMcpHandler.stopRedirectReason.replaceAll("'", "'\\''");
  return '''
#!/usr/bin/env bash
# Generated by TeamPilot — flashskyai mixed Stop → /idle. Do not edit.
set -u
cat >/dev/null 2>&1 || true
resp="\$(curl -sS -X POST $headerArgs '${idle.url}' 2>/dev/null || true)"
case "\$resp" in
  *'"decision":"block"'*)
    printf '%s\\n' '$reason' >&2
    exit 2
    ;;
esac
exit 0
''';
}

/// Install a command Stop hook that runs [scriptPath] (idempotent by path).
Map<String, Object?> mergeFlashskyaiStopIdleHook(
  Map<String, Object?> settings,
  String scriptPath,
) {
  final hooks = Map<String, Object?>.from(
    (settings['hooks'] as Map?)?.cast<String, Object?>() ?? const {},
  );
  final stop = List<Object?>.from((hooks['Stop'] as List?) ?? const []);
  final command = "bash '$scriptPath'";
  final exists = stop.any(
    (e) =>
        e is Map &&
        (e['hooks'] as List?)?.any(
              (h) => h is Map && h['type'] == 'command' && h['command'] == command,
            ) ==
            true,
  );
  if (!exists) {
    stop.add({
      'hooks': [
        {
          'type': 'command',
          'command': command,
          // Status / idle only — do not sit on the CLI default timeout.
          'timeout': 5,
        },
      ],
    });
  }
  hooks['Stop'] = stop;
  return {...settings, 'hooks': hooks};
}
