import '../../../agent_status/member_agent_status_endpoint.dart';
import '../../../host/host_script_dialect.dart';

/// Generates Codex command-hook scripts for HTTP POST (bash / PowerShell).
abstract final class CodexHttpHookScript {
  CodexHttpHookScript._();

  static String build({
    required HostScriptDialect dialect,
    required Map<String, String> headers,
    String? url,
    String? urlEnvKey,
    String? eventQueryValue,
    String? jsonBody,
    bool passResponseToStdout = false,
    bool bestEffort = false,
    bool forwardStdin = false,
  }) {
    assert(
      url != null || urlEnvKey != null,
      'Either url or urlEnvKey must be provided',
    );
    return switch (dialect) {
      HostScriptDialect.bash => _bash(
        url: url,
        urlEnvKey: urlEnvKey,
        eventQueryValue: eventQueryValue,
        headers: headers,
        jsonBody: jsonBody,
        passResponseToStdout: passResponseToStdout,
        bestEffort: bestEffort,
        forwardStdin: forwardStdin,
      ),
      HostScriptDialect.powershell => _powershell(
        url: url,
        urlEnvKey: urlEnvKey,
        eventQueryValue: eventQueryValue,
        headers: headers,
        jsonBody: jsonBody,
        passResponseToStdout: passResponseToStdout,
        bestEffort: bestEffort,
        forwardStdin: forwardStdin,
      ),
    };
  }

  static String buildAgentStatus({
    required HostScriptDialect dialect,
    required Map<String, String> headers,
    required String event,
  }) {
    return build(
      dialect: dialect,
      headers: headers,
      urlEnvKey: agentStatusUrlEnvKey,
      eventQueryValue: event,
      // Forward the real hook payload from stdin so tool / permission info
      // reaches `/agent-status` (Codex's payload mirrors Claude Code's keys).
      jsonBody: null,
      bestEffort: true,
      forwardStdin: true,
    );
  }

  static String _bash({
    required String? url,
    required String? urlEnvKey,
    required String? eventQueryValue,
    required Map<String, String> headers,
    required String? jsonBody,
    required bool passResponseToStdout,
    required bool bestEffort,
    required bool forwardStdin,
  }) {
    final headerArgs = headers.entries
        .map((e) => "-H ${_bashSingleQuote('${e.key}: ${e.value}')}")
        .join(' ');
    final bodyArg = jsonBody == null ? '' : '-d ${_bashSingleQuote(jsonBody)} ';
    final dataArg = forwardStdin ? '-d "\$payload" ' : bodyArg;
    final payloadProbe = forwardStdin
        ? 'payload="\$(cat)"\nif [ -z "\$payload" ]; then exit 0; fi\n'
        : '';
    final urlExpr = _bashUrlExpr(
      url: url,
      urlEnvKey: urlEnvKey,
      eventQueryValue: eventQueryValue,
    );
    final onFailure = bestEffort
        ? ' || true'
        : passResponseToStdout
        ? ' || echo {}'
        : ' || exit 1';
    final redirect = passResponseToStdout ? '' : ' >/dev/null';
    return '''
#!/usr/bin/env bash
# Generated by TeamPilot — codex HTTP hook. Do not edit.
set -u
$urlExpr
$payloadProbe
curl -sS --noproxy '*' -X POST $headerArgs $dataArg"\$url"$redirect$onFailure
exit 0
''';
  }

  static String _powershell({
    required String? url,
    required String? urlEnvKey,
    required String? eventQueryValue,
    required Map<String, String> headers,
    required String? jsonBody,
    required bool passResponseToStdout,
    required bool bestEffort,
    required bool forwardStdin,
  }) {
    final headerArgs = headers.entries
        .map((e) => "-H ${_psSingleQuote('${e.key}: ${e.value}')}")
        .join(' ');
    final bodyArg = jsonBody == null ? '' : "-d ${_psSingleQuote(jsonBody)} ";
    final dataArg = forwardStdin ? '-d \$payload ' : bodyArg;
    final payloadProbe = forwardStdin
        ? '\$payload = [Console]::In.ReadToEnd()\n'
              'if ([string]::IsNullOrWhiteSpace(\$payload)) { exit 0 }\n'
        : '';
    final urlSetup = _powershellUrlSetup(
      url: url,
      urlEnvKey: urlEnvKey,
      eventQueryValue: eventQueryValue,
    );
    if (passResponseToStdout) {
      return '''
# Generated by TeamPilot — codex HTTP hook. Do not edit.
$urlSetup
$payloadProbe
\$output = & curl.exe -sS --noproxy '*' -X POST $headerArgs $dataArg\$url 2>\$null
if (\$LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace(\$output)) {
  \$output = '{}'
}
Write-Output \$output
exit 0
''';
    }
    if (bestEffort) {
      return '''
# Generated by TeamPilot — codex HTTP hook. Do not edit.
$urlSetup
$payloadProbe
& curl.exe -sS --noproxy '*' -X POST $headerArgs $dataArg\$url 2>\$null | Out-Null
exit 0
''';
    }
    return '''
# Generated by TeamPilot — codex HTTP hook. Do not edit.
$urlSetup
$payloadProbe
& curl.exe -sS --noproxy '*' -X POST $headerArgs $dataArg\$url 2>\$null | Out-Null
if (\$LASTEXITCODE -ne 0) { exit 1 }
exit 0
''';
  }

  static String _bashUrlExpr({
    required String? url,
    required String? urlEnvKey,
    required String? eventQueryValue,
  }) {
    if (url != null) {
      return 'url=${_bashSingleQuote(url)}';
    }
    final envKey = urlEnvKey!;
    final event = eventQueryValue ?? '';
    return '''
base="\${$envKey:-}"
if [ -z "\$base" ]; then exit 0; fi
if [ -n ${_bashSingleQuote(event)} ]; then
  case "\$base" in
    *'?'*) url="\${base}&event=$event" ;;
    *) url="\${base}?event=$event" ;;
  esac
else
  url="\$base"
fi''';
  }

  static String _powershellUrlSetup({
    required String? url,
    required String? urlEnvKey,
    required String? eventQueryValue,
  }) {
    if (url != null) {
      return "\$url = ${_psSingleQuote(url)}";
    }
    final envKey = urlEnvKey!;
    final event = eventQueryValue ?? '';
    return '''
\$baseUrl = \$env:$envKey
if ([string]::IsNullOrWhiteSpace(\$baseUrl)) { exit 0 }
if ([string]::IsNullOrWhiteSpace(${_psSingleQuote(event)})) {
  \$url = \$baseUrl
} elseif (\$baseUrl.Contains('?')) {
  \$url = "\$baseUrl&event=$event"
} else {
  \$url = "\$baseUrl?event=$event"
}''';
  }

  static String _bashSingleQuote(String value) =>
      "'${value.replaceAll("'", "'\\''")}'";

  static String _psSingleQuote(String value) =>
      "'${value.replaceAll("'", "''")}'";
}
