import '../../../../models/launch_security_policy.dart';

/// Codex sandbox settings required for TeamPilot-managed HTTP hooks.
abstract final class CodexManagedHookOverlay {
  CodexManagedHookOverlay._();

  static String build({required LaunchSecurityPolicy launchSecurityPolicy}) {
    final buffer = StringBuffer(
      '# Generated by TeamPilot — codex managed-hook sandbox. Do not edit.',
    );
    if (launchSecurityPolicy.requiresDangerousExecution) {
      buffer.writeln();
      buffer.writeln('sandbox_mode = "danger-full-access"');
    }
    buffer.writeln();
    buffer.writeln('[sandbox_workspace_write]');
    buffer.writeln('network_access = true');
    return buffer.toString().trim();
  }

  static bool containsOverlay(String toml) =>
      toml.contains('codex managed-hook sandbox');
}
