import '../../../agent_status/member_agent_status_endpoint.dart';
import '../../../host/host_script_dialect.dart';
import '../../../host/host_script_runner.dart';
import '../../../io/filesystem.dart';
import 'codex_command_hook_provisioner.dart';
import 'codex_http_hook_script.dart';

/// Agent-status hooks appended to a member's Codex `config.toml`.
///
/// Installed whenever [MemberAgentStatusEndpoint] is stamped (simple + team),
/// not gated on mixed mode. Mixed-only Stop→`/idle` stays in
/// [CodexTeamBusOverlay].
abstract final class CodexAgentStatusOverlay {
  CodexAgentStatusOverlay._();

  static const _events = [
    'PermissionRequest',
    'PreToolUse',
    'PostToolUse',
    'PostToolUseFailure',
    'Stop',
    'StopFailure',
    'UserPromptSubmit',
  ];

  static const _hooksDirName = 'hooks';
  static const _scriptBasePrefix = 'teampilot-agent-status';

  /// Provisions per-event hook scripts and returns the TOML fragment.
  static Future<String> provision({
    required Filesystem fs,
    required HostScriptRunner runner,
    required String codexHome,
    required String memberId,
    required MemberAgentStatusEndpoint endpoint,
  }) async {
    final hooksDir = fs.pathContext.join(codexHome, _hooksDirName);
    final provisioner = CodexCommandHookProvisioner(fs: fs, runner: runner);
    final headers = {
      ...endpoint.headersFor(memberId),
      'Content-Type': 'application/json',
    };
    final buffer = StringBuffer(
      '# Generated by TeamPilot — codex agent-status hooks. Do not edit.',
    );

    for (final event in _events) {
      final commands = await provisioner.provisionHookCommands(
        hooksDir: hooksDir,
        baseFileName: '$_scriptBasePrefix-$event',
        scriptBody: CodexHttpHookScript.buildAgentStatus(
          dialect: HostScriptDialect.bash,
          headers: headers,
          event: event,
        ),
        windowsScriptBody: CodexHttpHookScript.buildAgentStatus(
          dialect: HostScriptDialect.powershell,
          headers: headers,
          event: event,
        ),
      );
      buffer
        ..writeln()
        ..writeln(
          provisioner.hookToml(
            event: event,
            command: commands.command,
            commandWindows: commands.commandWindows,
          ),
        );
    }

    return buffer.toString().trim();
  }

  static bool containsOverlay(String toml) =>
      toml.contains('codex agent-status hooks');
}
